# Generated by Django 5.2.3 on 2026-05-08 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('leave_type', models.CharField(choices=[('annual_leave', 'Yıllık İzin'), ('sick_leave', 'Hastalık İzni'), ('maternity_leave', 'Doğum İzni'), ('paternity_leave', 'Babalık İzni'), ('bereavement_leave', 'Ölüm İzni'), ('marriage_leave', 'Evlilik İzni'), ('public_duty', 'Resmi Görev'), ('compensatory_leave', 'Mazeret İzni'), ('business_trip', 'Görev Seyahati'), ('half_day', 'Yarım Gün'), ('paid_leave', 'Ücretli İzin'), ('unpaid_leave', 'Ücretsiz İzin')], max_length=30)),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'year', 'leave_type'],
                'unique_together': {('user', 'year', 'leave_type')},
            },
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=50)),
                ('leave_type', models.CharField(choices=[('annual_leave', 'Yıllık İzin'), ('sick_leave', 'Hastalık İzni'), ('maternity_leave', 'Doğum İzni'), ('paternity_leave', 'Babalık İzni'), ('bereavement_leave', 'Ölüm İzni'), ('marriage_leave', 'Evlilik İzni'), ('public_duty', 'Resmi Görev'), ('compensatory_leave', 'Mazeret İzni'), ('business_trip', 'Görev Seyahati'), ('half_day', 'Yarım Gün'), ('paid_leave', 'Ücretli İzin'), ('unpaid_leave', 'Ücretsiz İzin')], default='annual_leave', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['start_date'], name='vacation_re_start_d_561ddf_idx'), models.Index(fields=['end_date'], name='vacation_re_end_dat_9b70ee_idx'), models.Index(fields=['status'], name='vacation_re_status_f6596b_idx'), models.Index(fields=['requester'], name='vacation_re_request_a54dbf_idx')],
            },
        ),
    ]
