# Generated by Django 5.2.3 on 2026-05-11 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_requests', '0002_seed_vacation_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userleavebalance',
            options={'ordering': ['user']},
        ),
        migrations.AlterUniqueTogether(
            name='userleavebalance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userleavebalance',
            name='total_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total annual leave days available (set by HR, includes carry-over).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='userleavebalance',
            name='used_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Days used (auto-managed by the system).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='userleavebalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userleavebalance',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='userleavebalance',
            name='year',
        ),
    ]
