# Generated by Django 5.2.3 on 2026-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_requests', '0003_alter_userleavebalance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavebalance',
            name='last_credited_date',
            field=models.DateField(blank=True, help_text='Date of the last anniversary credit. Set by the credit_annual_leave command.', null=True),
        ),
    ]
