# Generated by Django 5.2.3 on 2026-05-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_requests', '0004_userleavebalance_last_credited_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='leave_type',
            field=models.CharField(choices=[('annual_leave', 'Yıllık İzin'), ('sick_leave', 'Hastalık İzni'), ('maternity_leave', 'Doğum İzni'), ('paternity_leave', 'Babalık İzni'), ('bereavement_leave', 'Ölüm İzni'), ('marriage_leave', 'Evlilik İzni'), ('public_duty', 'Resmi Görev'), ('compensatory_leave', 'Mazeret İzni'), ('business_trip', 'Görev Seyahati'), ('paid_leave', 'Ücretli İzin'), ('unpaid_leave', 'Ücretsiz İzin')], default='annual_leave', max_length=30),
        ),
    ]
