# Generated by Django 5.2.3 on 2026-05-11 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_requests', '0005_add_compensatory_time_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hr_adjustment', 'HR Düzeltmesi'), ('anniversary_credit', 'Yıllık Kredi'), ('request_deduct', 'İzin Talebi Kesintisi'), ('request_refund', 'İzin Talebi İadesi')], max_length=30)),
                ('delta', models.DecimalField(decimal_places=1, help_text='Positive = added, negative = deducted.', max_digits=6)),
                ('balance_after', models.DecimalField(decimal_places=1, help_text='Remaining days after this entry.', max_digits=6)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_balance_log_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance_logs', to=settings.AUTH_USER_MODEL)),
                ('vacation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_logs', to='vacation_requests.vacationrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
