# Generated by Django 5.2.3 on 2026-05-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_requests', '0006_add_leave_balance_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='is_company_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi'), ('cancellation_requested', 'İptal Talebi Bekliyor')], default='submitted', max_length=30),
        ),
    ]
