# Generated by Django 5.2.3 on 2025-06-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='used_in',
            field=models.CharField(max_length=50),
        ),
    ]
