# Generated by Django 5.2.3 on 2025-06-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_machine_is_under_maintenance_machinefault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='is_under_maintenance',
        ),
    ]
