# Generated by Django 5.2.3 on 2025-06-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_remove_machine_is_under_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinefault',
            name='is_resolved',
        ),
    ]
