# Generated by Django 5.2.3 on 2025-06-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_remove_machinefault_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinefault',
            name='is_breaking',
            field=models.BooleanField(default=True),
        ),
    ]
