# Generated by Django 5.2.3 on 2025-06-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_machinefault_is_breaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinefault',
            name='is_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
