# Generated by Django 5.2.3 on 2025-06-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_machinefault_is_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinefault',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
    ]
