# Generated by Django 5.2.3 on 2025-06-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_alter_machinefault_is_breaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinefault',
            name='resolution_description',
            field=models.TextField(default=''),
        ),
    ]
