# Generated by Django 5.2.3 on 2025-06-30 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_machinefault_resolution_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machinefault',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faults_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machinefault',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faults_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
