# Generated by Django 5.2.3 on 2025-08-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_machinefault_resolved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='used_in',
            field=models.CharField(choices=[('machining', 'Talaşlı İmalat'), ('design', 'Dizayn'), ('logistics', 'Lojistik'), ('procurement', 'Satın Alma'), ('welding', 'Kaynaklı İmalat'), ('planning', 'Planlama'), ('manufacturing', 'İmalat'), ('maintenance', 'Bakım'), ('rollingmill', 'Haddehane'), ('qualitycontrol', 'Kalite Kontrol'), ('cutting', 'CNC Kesim'), ('warehouse', 'Ambar'), ('finance', 'Finans')], max_length=50),
        ),
    ]
