# Generated by Django 5.2.3 on 2025-09-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_alter_machine_used_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('FTB', 'Zemin Tipi Manuel Borwerk'), ('TTB', 'Tabla Tipi Manuel Borwerk'), ('HM', 'Yatay İşleme Merkezi'), ('HT', 'Yatay Tornalama Merkezi'), ('VM', 'Dik İşleme Merkezi'), ('DM', 'Matkap'), ('SM', 'Kama Kanalı Açma Tezgahı'), ('BT', 'Köprü Tipi İşleme Merkezi'), ('ACT', 'AJAN Sac Kesim Tezgahı'), ('ECT', 'ESAB Sac Kesim Tezgahı'), ('CTEDO', 'Dolap Tipi Elektrot Kurutma Fırını'), ('OC', 'Tavan Vinci'), ('WD', 'Kaynak Makinesi')], max_length=10),
        ),
    ]
