# Generated by Django 5.2.3 on 2025-09-10 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0012_alter_machine_machine_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Europe/Istanbul', max_length=64)),
                ('week_template', models.JSONField(blank=True, default=dict)),
                ('machine_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='machines.machine')),
            ],
        ),
    ]
