# Generated by Django 5.2.3 on 2025-09-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0013_machinecalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinecalendar',
            name='work_exceptions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
