# Generated by Django 5.2.3 on 2025-09-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0016_machine_assigned_users_alter_machine_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='used_in',
            field=models.CharField(choices=[('machining', 'Talaşlı İmalat'), ('design', 'Dizayn'), ('logistics', 'Lojistik'), ('procurement', 'Satın Alma'), ('welding', 'Kaynaklı İmalat'), ('planning', 'Planlama'), ('manufacturing', 'İmalat'), ('maintenance', 'Bakım'), ('rollingmill', 'Haddehane'), ('qualitycontrol', 'Kalite Kontrol'), ('cutting', 'CNC Kesim'), ('warehouse', 'Ambar'), ('finance', 'Finans'), ('it', 'Bilgi İşlem'), ('sales', 'Proje Taahhüt')], max_length=50),
        ),
    ]
