# Generated by Django 5.2.3 on 2025-10-09 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0018_alter_machine_used_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machinefault',
            name='area',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='asset_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='asset_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faults_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='machinefault',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faults', to='machines.machine'),
        ),
        migrations.AlterField(
            model_name='machinefault',
            name='resolution_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='machinefault',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faults_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='machinefault',
            index=models.Index(fields=['machine'], name='machines_ma_machine_ca9547_idx'),
        ),
        migrations.AddIndex(
            model_name='machinefault',
            index=models.Index(fields=['resolved_at'], name='machines_ma_resolve_174ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='machinefault',
            index=models.Index(fields=['is_breaking'], name='machines_ma_is_brea_b343c4_idx'),
        ),
        migrations.AddIndex(
            model_name='machinefault',
            index=models.Index(fields=['is_maintenance'], name='machines_ma_is_main_2e1ba0_idx'),
        ),
    ]
