# Generated by Django 5.2.3 on 2025-10-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0019_machinefault_area_machinefault_asset_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinefault',
            name='area',
        ),
        migrations.RemoveField(
            model_name='machinefault',
            name='asset_code',
        ),
    ]
