# Generated by Django 5.2.3 on 2026-01-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0021_alter_machine_machine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinefault',
            name='downtime_end_ms',
            field=models.BigIntegerField(blank=True, help_text='When machine became available again (ms)', null=True),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='downtime_start_ms',
            field=models.BigIntegerField(blank=True, help_text='When machine became unavailable (ms)', null=True),
        ),
    ]
