# Generated by Django 5.2.3 on 2026-04-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0022_machinefault_downtime_end_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('FTB', 'Zemin Tipi Manuel Borwerk'), ('TTB', 'Tabla Tipi Manuel Borwerk'), ('HM', 'Yatay İşleme Merkezi'), ('HT', 'Yatay Tornalama Merkezi'), ('VM', 'Dik İşleme Merkezi'), ('DM', 'Matkap'), ('SM', 'Kama Kanalı Açma Tezgahı'), ('BT', 'Köprü Tipi İşleme Merkezi'), ('ACT', 'AJAN Sac Kesim Tezgahı'), ('ECT', 'ESAB Sac Kesim Tezgahı'), ('CTEDO', 'Dolap Tipi Elektrot Kurutma Fırını'), ('OC', 'Tavan Vinci'), ('WD', 'Kaynak Makinesi'), ('AWD', 'Argon Kaynak Makinesi'), ('EWD', 'Elektrik Kaynak Makinesi'), ('SWD', 'Tozaltı Kaynak Makinesi'), ('3PB', 'Üç Silindirli Sac Büküm Makinesi'), ('LAPTOP', 'Dizüstü Bilgisayar'), ('BKS', 'Band Kesim Tezgahı'), ('DKS', 'Daire Kesim Tezgahı'), ('PKES', 'Profil Kesim Makinesi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='used_in',
            field=models.CharField(choices=[('machining', 'Talaşlı İmalat'), ('design', 'Dizayn'), ('logistics', 'Lojistik'), ('procurement', 'Satın Alma'), ('welding', 'Kaynaklı İmalat'), ('planning', 'Planlama'), ('manufacturing', 'İmalat'), ('maintenance', 'Bakım'), ('rollingmill', 'Haddehane'), ('qualitycontrol', 'Kalite Kontrol'), ('cutting', 'CNC Kesim'), ('linear_cutting', 'Lineer Kesim'), ('warehouse', 'Ambar'), ('finance', 'Finans'), ('it', 'Bilgi İşlem'), ('sales', 'Proje Taahhüt'), ('accounting', 'Muhasebe')], max_length=50),
        ),
    ]
