# Generated by Django 5.2.3 on 2026-05-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waiting_info', 'Waiting for Info'), ('in_progress', 'In Progress'), ('pr_created', 'PR Created'), ('escalated', 'Escalated to Staff'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
