# Generated by Django 5.2.3 on 2026-05-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reports', '0002_alter_bugreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='page_label',
            field=models.CharField(blank=True, help_text='Human-readable page name', max_length=255),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='page_url',
            field=models.CharField(blank=True, help_text='Frontend route where the bug occurred', max_length=255),
        ),
    ]
