# Generated by Django 5.2.3 on 2025-06-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
