# Generated by Django 5.2.3 on 2025-06-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_must_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.CharField(blank=True, choices=[('machining', 'Talaşlı İmalat'), ('design', 'Dizayn'), ('logistics', 'Lojistik'), ('procurement', 'Satın Alma'), ('welding', 'Kaynaklı İmalat'), ('planning', 'Planlama'), ('manufacturing', 'İmalat')], max_length=50, null=True),
        ),
    ]
