# Generated by Django 5.2.3 on 2025-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jira_api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
