# Generated by Django 5.2.3 on 2025-07-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_jira_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
