# Generated by Django 5.2.3 on 2025-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_is_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.CharField(blank=True, choices=[('machining', 'Talaşlı İmalat'), ('design', 'Dizayn'), ('logistics', 'Lojistik'), ('procurement', 'Satın Alma'), ('welding', 'Kaynaklı İmalat'), ('planning', 'Planlama'), ('manufacturing', 'İmalat'), ('maintenance', 'Bakım'), ('rollingmill', 'Haddehane'), ('qualitycontrol', 'Kalite Kontrol')], max_length=50, null=True),
        ),
    ]
