# Generated by Django 5.2.3 on 2025-07-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('manager', 'Müdür'), ('welder', 'Kaynakçı'), ('foreman', 'Formen'), ('assembler', 'Montajcı'), ('helper', 'Yardımcı')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.CharField(blank=True, choices=[('machining', 'Talaşlı İmalat'), ('design', 'Dizayn'), ('logistics', 'Lojistik'), ('procurement', 'Satın Alma'), ('welding', 'Kaynaklı İmalat'), ('planning', 'Planlama'), ('manufacturing', 'İmalat'), ('maintenance', 'Bakım'), ('rollingmill', 'Haddehane'), ('qualitycontrol', 'Kalite Kontrol'), ('cutting', 'CNC Kesim'), ('warehouse', 'Ambar')], max_length=50, null=True),
        ),
    ]
