# Generated by Django 5.2.3 on 2025-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_occupation_alter_userprofile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('manager', 'Müdür'), ('welder', 'Kaynakçı'), ('foreman', 'Formen'), ('assembler', 'Montajcı'), ('helper', 'Yardımcı'), ('operator', 'Operatör'), ('office', 'Ofis çalışanı')], max_length=50, null=True),
        ),
    ]
