# Generated by Django 5.2.3 on 2025-07-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userprofile_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='collar_type',
            field=models.CharField(choices=[('blue', 'Mavi Yaka'), ('white', 'Beyaz Yaka')], default='blue', max_length=10),
        ),
    ]
