# Generated by Django 5.2.3 on 2025-07-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_collar_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='collar_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_location',
            field=models.CharField(choices=[('workshop', 'Atölye'), ('office', 'Ofis')], default='workshop', max_length=10),
        ),
    ]
