# Generated by Django 5.2.3 on 2025-09-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_userprofile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_request',
            field=models.BooleanField(default=False),
        ),
    ]
