# Generated by Django 5.2.3 on 2025-09-26 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_userprofile_reset_password_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(db_index=True)),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=3)),
                ('base_monthly', models.DecimalField(decimal_places=4, max_digits=12)),
                ('base_hourly', models.DecimalField(decimal_places=4, max_digits=12)),
                ('after_hours_multiplier', models.DecimalField(decimal_places=3, default=1.5, max_digits=6)),
                ('sunday_multiplier', models.DecimalField(decimal_places=3, default=2.0, max_digits=6)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_wage', 'Can view wages'), ('add_wage', 'Can add wages'), ('change_wage', 'Can change wages'), ('delete_wage', 'Can delete wages')],
                'indexes': [models.Index(fields=['user', 'effective_from'], name='users_wager_user_id_301e45_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'effective_from'), name='uniq_user_wage_effective_from')],
            },
        ),
    ]
