# Generated by Django 5.2.3 on 2025-09-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_wagerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wagerate',
            name='base_hourly',
        ),
    ]
