# Generated by Django 5.2.3 on 2026-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_permissionmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmeta',
            name='section',
            field=models.CharField(blank=True, choices=[('workshop', 'Workshop'), ('manufacturing', 'Manufacturing'), ('design', 'Design'), ('finance', 'Finance'), ('general', 'General'), ('human_resources', 'Human Resources'), ('it', 'IT'), ('logistics', 'Logistics'), ('management', 'Management'), ('planning', 'Planning'), ('procurement', 'Procurement'), ('projects', 'Projects'), ('quality_control', 'Quality Control'), ('sales', 'Sales'), ('accounting', 'Accounting')], max_length=50, null=True),
        ),
    ]
