# Generated by Django 5.2.3 on 2026-04-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_shiftrule_options_and_more'),
        ('users', '0034_alter_permissionmeta_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shift_rule',
            field=models.ForeignKey(blank=True, help_text='Explicit shift rule for this user. If blank, the default shift rule is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='attendance.shiftrule'),
        ),
    ]
