# Generated by Django 5.2.3 on 2026-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_userprofile_shift_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Official employment start date. Used to calculate annual leave entitlement.', null=True),
        ),
    ]
