# Generated by Django 5.2.3 on 2026-05-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_userprofile_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date of birth. Used for age-based leave entitlement (under 18 / over 50 → min 20 days).', null=True),
        ),
    ]
