# Generated by Django 5.2.3 on 2026-05-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_backfill_userprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='jira_api_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='work_location',
        ),
    ]
