# Generated by Django 5.2.3 on 2026-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_remove_occupation_jira_work_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Erkek'), ('F', 'Kadın')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personel_kodu',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sigorta_yuzde_grubu',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('emekli', 'Emekli')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tc_kimlik_no',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
