# Generated by Django 5.2.3 on 2026-02-19 06:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0018_joborder_total_weight_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorCostRecalcQueue',
            fields=[
                ('job_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('enqueued_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subcontracting_cost_recalc_queue',
            },
        ),
        migrations.CreateModel(
            name='SubcontractingPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Ağır Plakalar", "Hafif Çerçeve"', max_length=200)),
                ('price_per_kg', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='TRY', max_length=3)),
                ('allocated_weight_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontracting_price_tiers', to='projects.joborder')),
            ],
            options={
                'verbose_name': 'Taşeron Fiyat Kademesi',
                'verbose_name_plural': 'Taşeron Fiyat Kademeleri',
                'ordering': ['job_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('tax_office', models.CharField(blank=True, max_length=100)),
                ('bank_info', models.TextField(blank=True)),
                ('agreement_details', models.TextField(blank=True)),
                ('default_currency', models.CharField(choices=[('TRY', 'TRY'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='TRY', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontractors_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taşeron',
                'verbose_name_plural': 'Taşeronlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_weight_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('cost_currency', models.CharField(choices=[('TRY', 'TRY'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='TRY', max_length=3)),
                ('last_billed_progress', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subcontracting_assignment', to='projects.joborderdepartmenttask')),
                ('price_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtask_assignments', to='subcontracting.subcontractingpricetier')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='subcontracting.subcontractor')),
            ],
            options={
                'verbose_name': 'Taşeron Ataması',
                'verbose_name_plural': 'Taşeron Atamaları',
            },
        ),
        migrations.CreateModel(
            name='SubcontractorStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('paid', 'Ödendi'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20)),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='TRY', max_length=3)),
                ('work_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('adjustment_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='subcontracting.subcontractor')),
            ],
            options={
                'verbose_name': 'Taşeron Hakedişi',
                'verbose_name_plural': 'Taşeron Hakedişleri',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractorStatementAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('addition', 'Ek Ödeme'), ('deduction', 'Kesinti')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for additions, negative for deductions', max_digits=16)),
                ('reason', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.joborder')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='subcontracting.subcontractorstatement')),
            ],
            options={
                'verbose_name': 'Hakediş Düzeltmesi',
                'verbose_name_plural': 'Hakediş Düzeltmeleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractorStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('subcontractor_name', models.CharField(max_length=200)),
                ('price_tier_name', models.CharField(max_length=200)),
                ('allocated_weight_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_progress', models.DecimalField(decimal_places=2, help_text='last_billed_progress at time of statement generation (already paid)', max_digits=5)),
                ('current_progress', models.DecimalField(decimal_places=2, help_text='manual_progress at time of statement generation', max_digits=5)),
                ('delta_progress', models.DecimalField(decimal_places=2, help_text='current_progress - previous_progress (what is being billed)', max_digits=5)),
                ('effective_weight_kg', models.DecimalField(decimal_places=2, help_text='allocated_weight_kg × delta_progress / 100', max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cost_amount', models.DecimalField(decimal_places=2, help_text='effective_weight_kg × price_per_kg', max_digits=16)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_lines', to='subcontracting.subcontractingassignment')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='subcontracting.subcontractorstatement')),
            ],
            options={
                'verbose_name': 'Hakediş Kalemi',
                'verbose_name_plural': 'Hakediş Kalemleri',
                'ordering': ['job_no', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='subcontractingassignment',
            index=models.Index(fields=['subcontractor'], name='subcontract_subcont_1633a3_idx'),
        ),
        migrations.AddIndex(
            model_name='subcontractingassignment',
            index=models.Index(fields=['price_tier'], name='subcontract_price_t_3268d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcontractorstatement',
            unique_together={('subcontractor', 'year', 'month')},
        ),
    ]
