# Generated by Django 5.2.3 on 2026-02-20 07:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontracting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractingpricetier',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
