# Generated by Django 5.2.3 on 2026-03-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontracting', '0003_adjustment_job_order_mandatory_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorstatement',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
