# Generated by Django 5.2.3 on 2026-03-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontracting', '0005_monthly_paint_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorstatement',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of employees working on this statement period (entered manually after creation)', null=True),
        ),
    ]
