# Generated by Django 5.2.3 on 2026-04-10 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontracting', '0009_retire_legacy_subcontractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractorstatementline',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_lines', to='subcontracting.subcontractingassignment'),
        ),
    ]
