# Generated by Django 5.2.3 on 2026-04-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontracting', '0010_nullable_statement_line_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractingpricetier',
            name='tier_type',
            field=models.CharField(choices=[('welding', 'Kaynaklı İmalat'), ('paint', 'Boya')], default='welding', max_length=10),
        ),
    ]
