# Generated by Django 5.2.3 on 2026-01-16 11:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_customer_created_at_alter_customer_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('job_no', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('active', 'Aktif'), ('on_hold', 'Beklemede'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], db_index=True, default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=20)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('subcontractor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('cost_currency', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini')], default='TRY', max_length=3)),
                ('last_cost_calculation', models.DateTimeField(blank=True, null=True)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_orders', to='projects.customer')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.joborder')),
            ],
            options={
                'verbose_name': 'İş Emri',
                'verbose_name_plural': 'İş Emirleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='projects_jo_status_f7ebfa_idx'), models.Index(fields=['customer', 'status'], name='projects_jo_custome_29c17f_idx'), models.Index(fields=['target_completion_date'], name='projects_jo_target__a50189_idx')],
            },
        ),
    ]
