# Generated by Django 5.2.3 on 2026-01-21 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_joborder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['code'], 'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.CreateModel(
            name='DepartmentTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departman Görevi Şablonu',
                'verbose_name_plural': 'Departman Görevi Şablonları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentTaskTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('design', 'Tasarım'), ('planning', 'Planlama'), ('procurement', 'Satın Alma'), ('manufacturing', 'Üretim'), ('painting', 'Boya'), ('logistics', 'Lojistik')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('requires_qc_approval', models.BooleanField(default=False)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='projects.departmenttasktemplateitem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.departmenttasktemplate')),
            ],
            options={
                'verbose_name': 'Şablon Öğesi',
                'verbose_name_plural': 'Şablon Öğeleri',
                'ordering': ['template', 'sequence'],
                'unique_together': {('template', 'department')},
            },
        ),
        migrations.CreateModel(
            name='JobOrderDepartmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('design', 'Tasarım'), ('planning', 'Planlama'), ('procurement', 'Satın Alma'), ('manufacturing', 'Üretim'), ('painting', 'Boya'), ('logistics', 'Lojistik')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('in_progress', 'Devam Ediyor'), ('blocked', 'Engellendi'), ('awaiting_qc', 'KK Onayı Bekliyor'), ('qc_approved', 'KK Onaylandı'), ('qc_rejected', 'KK Reddedildi'), ('completed', 'Tamamlandı'), ('skipped', 'Atlandı')], db_index=True, default='pending', max_length=20)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocker_reason', models.TextField(blank=True, null=True)),
                ('requires_qc_approval', models.BooleanField(default=False)),
                ('qc_approved_at', models.DateTimeField(blank=True, null=True)),
                ('qc_rejection_reason', models.TextField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_department_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='projects.joborderdepartmenttask')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_tasks', to='projects.joborder')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projects.joborderdepartmenttask')),
                ('qc_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_approved_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departman Görevi',
                'verbose_name_plural': 'Departman Görevleri',
                'ordering': ['job_order', 'sequence'],
                'indexes': [models.Index(fields=['department', 'status'], name='projects_jo_departm_094423_idx'), models.Index(fields=['assigned_to', 'status'], name='projects_jo_assigne_f1cb62_idx'), models.Index(fields=['job_order', 'parent'], name='projects_jo_job_ord_96ecc9_idx')],
            },
        ),
    ]
