# Generated by Django 5.2.3 on 2026-01-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_customer_options_departmenttasktemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenttasktemplateitem',
            name='requires_qc_approval',
        ),
        migrations.RemoveField(
            model_name='joborderdepartmenttask',
            name='qc_approved_at',
        ),
        migrations.RemoveField(
            model_name='joborderdepartmenttask',
            name='qc_approved_by',
        ),
        migrations.RemoveField(
            model_name='joborderdepartmenttask',
            name='qc_rejection_reason',
        ),
        migrations.RemoveField(
            model_name='joborderdepartmenttask',
            name='requires_qc_approval',
        ),
        migrations.AlterField(
            model_name='joborderdepartmenttask',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('in_progress', 'Devam Ediyor'), ('blocked', 'Engellendi'), ('completed', 'Tamamlandı'), ('skipped', 'Atlandı')], db_index=True, default='pending', max_length=20),
        ),
    ]
