# Generated by Django 5.2.3 on 2026-01-23 08:46

import core.storages
import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_departmenttasktemplateitem_requires_qc_approval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborderdepartmenttask',
            name='blocker_reason',
        ),
        migrations.RemoveField(
            model_name='joborderdepartmenttask',
            name='is_blocked',
        ),
        migrations.AlterField(
            model_name='departmenttasktemplateitem',
            name='department',
            field=models.CharField(choices=[('design', 'Dizayn'), ('planning', 'Planlama'), ('procurement', 'Satın Alma'), ('manufacturing', 'Üretim'), ('painting', 'Boya'), ('logistics', 'Lojistik')], max_length=50),
        ),
        migrations.AlterField(
            model_name='departmenttasktemplateitem',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='cost_currency',
            field=models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='joborderdepartmenttask',
            name='department',
            field=models.CharField(choices=[('design', 'Dizayn'), ('planning', 'Planlama'), ('procurement', 'Satın Alma'), ('manufacturing', 'Üretim'), ('painting', 'Boya'), ('logistics', 'Lojistik')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='joborderdepartmenttask',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('skipped', 'Atlandı')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='joborderdepartmenttask',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='JobOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=core.storages.PrivateMediaStorage(), upload_to=projects.models.job_order_file_upload_path)),
                ('file_type', models.CharField(choices=[('drawing', 'Çizim'), ('specification', 'Şartname'), ('contract', 'Sözleşme'), ('correspondence', 'Yazışma'), ('photo', 'Fotoğraf'), ('other', 'Diğer')], default='other', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.joborder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_job_order_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İş Emri Dosyası',
                'verbose_name_plural': 'İş Emri Dosyaları',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
