# Generated by Django 5.2.3 on 2026-01-26 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_joborderdepartmenttask_blocker_reason_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmenttasktemplateitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='departmenttasktemplateitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.departmenttasktemplateitem'),
        ),
    ]
