# Generated by Django 5.2.3 on 2026-01-26 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_departmenttasktemplateitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttasktemplateitem',
            name='weight',
            field=models.PositiveIntegerField(default=10, help_text='Görev ağırlığı (1-100 puan). Varsayılan: 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='joborderdepartmenttask',
            name='weight',
            field=models.PositiveIntegerField(default=10, help_text='Görev ağırlığı (1-100 puan). Varsayılan: 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
