# Generated by Django 5.2.3 on 2026-01-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_departmenttasktemplateitem_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborderdepartmenttask',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('blocked', 'Engellenmiş'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('skipped', 'Atlandı')], db_index=True, default='pending', max_length=20),
        ),
    ]
