# Generated by Django 5.2.3 on 2026-02-02 13:29

import core.storages
import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_joborderdepartmenttask_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborderdepartmenttask',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('blocked', 'Engellenmiş'), ('in_progress', 'Devam Ediyor'), ('on_hold', 'Askıda'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('skipped', 'Atlandı')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='JobOrderDiscussionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], db_index=True, default='normal', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_topics_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_topics_deleted', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topics', to='projects.joborder')),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='discussion_topics_mentioned_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOrderDiscussionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_comments_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_comments_deleted', to=settings.AUTH_USER_MODEL)),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='discussion_comments_mentioned_in', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.joborderdiscussiontopic')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('topic_mention', 'Konuda Etiketlendi'), ('comment_mention', 'Yorumda Etiketlendi'), ('new_comment', 'Yeni Yorum')], db_index=True, max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_emailed', models.BooleanField(default=False)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_notifications', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.joborderdiscussioncomment')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.joborderdiscussiontopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=core.storages.PrivateMediaStorage(), upload_to=projects.models.discussion_attachment_upload_path)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.joborderdiscussioncomment')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.joborderdiscussiontopic')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='joborderdiscussiontopic',
            index=models.Index(fields=['job_order', 'is_deleted'], name='projects_jo_job_ord_306711_idx'),
        ),
        migrations.AddIndex(
            model_name='joborderdiscussiontopic',
            index=models.Index(fields=['created_by', 'created_at'], name='projects_jo_created_568e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='joborderdiscussiontopic',
            index=models.Index(fields=['priority', 'created_at'], name='projects_jo_priorit_67759f_idx'),
        ),
        migrations.AddIndex(
            model_name='joborderdiscussioncomment',
            index=models.Index(fields=['topic', 'is_deleted', 'created_at'], name='projects_jo_topic_i_20edf4_idx'),
        ),
        migrations.AddIndex(
            model_name='joborderdiscussioncomment',
            index=models.Index(fields=['created_by', 'created_at'], name='projects_jo_created_68a2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionnotification',
            index=models.Index(fields=['user', 'is_read'], name='projects_di_user_id_4b2393_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionnotification',
            index=models.Index(fields=['user', 'notification_type', 'created_at'], name='projects_di_user_id_1894e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discussionnotification',
            unique_together={('user', 'topic', 'comment', 'notification_type')},
        ),
    ]
