# Generated by Django 5.2.3 on 2026-02-04 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_joborderdepartmenttask_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joborderdiscussiontopic',
            name='revision_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_revision_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joborderdiscussiontopic',
            name='revision_status',
            field=models.CharField(blank=True, choices=[('pending', 'Onay Bekliyor'), ('in_progress', 'Devam Ediyor'), ('resolved', 'Çözüldü'), ('rejected', 'Reddedildi')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='joborderdiscussiontopic',
            name='topic_type',
            field=models.CharField(choices=[('general', 'Genel'), ('drawing_release', 'Çizim Yayını'), ('revision_request', 'Revizyon Talebi')], db_index=True, default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='discussionnotification',
            name='notification_type',
            field=models.CharField(choices=[('topic_mention', 'Konuda Etiketlendi'), ('comment_mention', 'Yorumda Etiketlendi'), ('new_comment', 'Yeni Yorum'), ('drawing_released', 'Çizim Yayınlandı'), ('revision_requested', 'Revizyon Talep Edildi'), ('revision_approved', 'Revizyon Onaylandı'), ('revision_completed', 'Revizyon Tamamlandı'), ('revision_rejected', 'Revizyon Reddedildi'), ('job_on_hold', 'İş Beklemede'), ('job_resumed', 'İş Devam Ediyor')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='joborderdiscussiontopic',
            name='priority',
            field=models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Önemli'), ('urgent', 'Çok Önemli')], db_index=True, default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='TechnicalDrawingRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('revision_code', models.CharField(blank=True, max_length=10)),
                ('folder_path', models.CharField(max_length=500)),
                ('changelog', models.TextField(help_text='Değişiklik açıklaması')),
                ('hardcopy_count', models.PositiveIntegerField(default=0, help_text='Hardcopy set sayısı')),
                ('status', models.CharField(choices=[('released', 'Yayınlandı'), ('in_revision', 'Revizyon Yapılıyor'), ('superseded', 'Güncelliğini Kaybetti')], db_index=True, default='released', max_length=20)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_order', models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='technical_drawing_releases', to='projects.joborder')),
                ('release_topic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_release', to='projects.joborderdiscussiontopic')),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teknik Çizim Yayını',
                'verbose_name_plural': 'Teknik Çizim Yayınları',
                'ordering': ['-revision_number'],
            },
        ),
        migrations.AddField(
            model_name='joborderdiscussiontopic',
            name='related_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_topics', to='projects.technicaldrawingrelease'),
        ),
        migrations.AddIndex(
            model_name='technicaldrawingrelease',
            index=models.Index(fields=['job_order', 'status'], name='projects_te_job_ord_d1dc97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicaldrawingrelease',
            unique_together={('job_order', 'revision_number')},
        ),
    ]
