# Generated by Django 5.2.3 on 2026-02-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_joborderdiscussiontopic_revision_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicaldrawingrelease',
            name='changelog',
            field=models.TextField(blank=True, help_text='Değişiklik açıklaması'),
        ),
    ]
