# Generated by Django 5.2.3 on 2026-02-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_technicaldrawingrelease_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='incoterms',
            field=models.CharField(blank=True, null=True),
        ),
    ]
