# Generated by Django 5.2.3 on 2026-02-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_joborder_incoterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
