# Generated by Django 5.2.3 on 2026-02-12 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_joborder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicaldrawingrelease',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_drawing_releases', to='projects.joborder'),
        ),
    ]
