# Generated by Django 5.2.3 on 2026-02-12 09:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_technicaldrawingrelease_job_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborderdepartmenttask',
            name='manual_progress',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
