# Generated by Django 5.2.3 on 2026-02-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_joborderdepartmenttask_manual_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='total_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total weight in kg (set by planning for subcontracting cost calculation)', max_digits=12, null=True),
        ),
    ]
