# Generated by Django 5.2.3 on 2026-02-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_joborder_total_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttasktemplateitem',
            name='task_type',
            field=models.CharField(blank=True, choices=[('cnc_cutting', 'CNC Kesim'), ('machining', 'Talaşlı İmalat'), ('welding', 'Kaynaklı İmalat')], help_text='Special task type — leave blank for regular tasks.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='joborderdepartmenttask',
            name='task_type',
            field=models.CharField(blank=True, choices=[('cnc_cutting', 'CNC Kesim'), ('machining', 'Talaşlı İmalat'), ('welding', 'Kaynaklı İmalat')], db_index=True, help_text='Special task type — drives progress calculation and subcontracting logic. Leave blank for regular tasks.', max_length=20, null=True),
        ),
    ]
