# Generated by Django 5.2.3 on 2026-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_add_part_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttasktemplateitem',
            name='task_type',
            field=models.CharField(blank=True, choices=[('cnc_cutting', 'CNC Kesim'), ('machining', 'Talaşlı İmalat'), ('welding', 'Kaynaklı İmalat'), ('painting', 'Boya')], help_text='Special task type — leave blank for regular tasks.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joborderdepartmenttask',
            name='task_type',
            field=models.CharField(blank=True, choices=[('cnc_cutting', 'CNC Kesim'), ('machining', 'Talaşlı İmalat'), ('welding', 'Kaynaklı İmalat'), ('painting', 'Boya')], db_index=True, help_text='Special task type — drives progress calculation and subcontracting logic. Leave blank for regular tasks.', max_length=20, null=True),
        ),
    ]
