# Generated by Django 5.2.3 on 2026-02-25 06:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_planningrequestitem_delivered_at_and_more'),
        ('procurement', '0035_purchaseorderline_delivered_at_and_more'),
        ('projects', '0022_alter_departmenttasktemplateitem_task_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderCostSummary',
            fields=[
                ('job_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cost_summary', serialize=False, to='projects.joborder')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Welding + machining cost (EUR)', max_digits=16)),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of procurement lines (EUR)', max_digits=16)),
                ('subcontractor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Non-paint subcontracting assignments (EUR)', max_digits=16)),
                ('paint_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Paint subcontracting assignments (EUR, using statement-date FX)', max_digits=16)),
                ('qc_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of QC cost lines (EUR)', max_digits=16)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of shipping cost lines (EUR)', max_digits=16)),
                ('actual_total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all cost components (EUR)', max_digits=16)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('selling_price_currency', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini')], default='EUR', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İş Emri Maliyet Özeti',
                'verbose_name_plural': 'İş Emri Maliyet Özetleri',
            },
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='cost_currency',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='labor_cost',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='last_cost_calculation',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='material_cost',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='subcontractor_cost',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='joborder',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='User-entered estimated cost (EUR) for comparison with actual cost.', max_digits=16),
        ),
        migrations.CreateModel(
            name='JobOrderProcurementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price in EUR', max_digits=16)),
                ('amount_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed server-side: quantity × unit_price', max_digits=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_cost_lines', to='procurement.item')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_lines', to='projects.joborder')),
                ('planning_request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_cost_lines', to='planning.planningrequestitem')),
            ],
            options={
                'verbose_name': 'Tedarik Maliyet Kalemi',
                'verbose_name_plural': 'Tedarik Maliyet Kalemleri',
                'ordering': ['job_order', 'order'],
                'indexes': [models.Index(fields=['job_order'], name='projects_jo_job_ord_4ea472_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobOrderQCCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini')], default='EUR', max_length=3)),
                ('amount_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='EUR equivalent (user-provided; server validates if currency=EUR)', max_digits=16)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_cost_lines_created', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_cost_lines', to='projects.joborder')),
            ],
            options={
                'verbose_name': 'KK Maliyet Kalemi',
                'verbose_name_plural': 'KK Maliyet Kalemleri',
                'ordering': ['job_order', '-date', 'id'],
                'indexes': [models.Index(fields=['job_order'], name='projects_jo_job_ord_ff6769_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobOrderShippingCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini')], default='EUR', max_length=3)),
                ('amount_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='EUR equivalent (user-provided; server validates if currency=EUR)', max_digits=16)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_cost_lines_created', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_cost_lines', to='projects.joborder')),
            ],
            options={
                'verbose_name': 'Nakliye Maliyet Kalemi',
                'verbose_name_plural': 'Nakliye Maliyet Kalemleri',
                'ordering': ['job_order', '-date', 'id'],
                'indexes': [models.Index(fields=['job_order'], name='projects_jo_job_ord_5b97c8_idx')],
            },
        ),
    ]
