# Generated by Django 5.2.3 on 2026-02-25 11:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_jobordercostsummary_remove_joborder_cost_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='general_expenses_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='General expenses rate in TRY per kg (multiplied by total_weight_kg to get general expenses cost)', max_digits=10),
        ),
        migrations.AddField(
            model_name='jobordercostsummary',
            name='employee_overhead_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='employee_overhead_rate × own labor_cost (EUR)', max_digits=16),
        ),
        migrations.AddField(
            model_name='jobordercostsummary',
            name='employee_overhead_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.60'), help_text='Multiplier applied to labor_cost to estimate employee overhead (default 0.60)', max_digits=6),
        ),
        migrations.AddField(
            model_name='jobordercostsummary',
            name='general_expenses_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='General expenses: general_expenses_rate (TRY/kg) × total_weight_kg → EUR', max_digits=16),
        ),
        migrations.AddField(
            model_name='jobordercostsummary',
            name='paint_material_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Paint material cost: 4.00 TRY × total_weight_kg → EUR (only if painting task not skipped)', max_digits=16),
        ),
    ]
