# Generated by Django 5.2.3 on 2026-02-25 11:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_add_cost_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='general_expenses_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.70'), help_text='General expenses rate in TRY per kg (multiplied by total_weight_kg to get general expenses cost)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobordercostsummary',
            name='employee_overhead_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.65'), help_text='Multiplier applied to labor_cost to estimate employee overhead (default 0.65)', max_digits=6),
        ),
    ]
