# Generated by Django 5.2.3 on 2026-02-25 11:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_update_cost_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobordercostsummary',
            name='paint_material_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('4.00'), help_text='Paint material rate in TRY per kg (default 4.00)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobordercostsummary',
            name='paint_material_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Paint material cost: paint_material_rate (TRY/kg) × total_weight_kg → EUR (only if painting task not skipped)', max_digits=16),
        ),
    ]
