# Generated by Django 5.2.3 on 2026-02-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_jobordercostsummary_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobordercostsummary',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
    ]
