# Generated by Django 5.2.3 on 2026-02-25 15:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_alter_jobordercostsummary_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobordercostsummary',
            name='other_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='other expenses', max_digits=16),
        ),
    ]
