# Generated by Django 5.2.3 on 2026-02-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_department_task_consultation_support'),
        ('projects', '0029_jobordercostsummary_other_cost'),
    ]

    operations = [
    ]
