# Generated by Django 5.2.3 on 2026-02-26 09:33

import core.storages
import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_merge_20260226_0859'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderDepartmentTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=core.storages.PrivateMediaStorage(), upload_to=projects.models.department_task_file_upload_path)),
                ('file_type', models.CharField(choices=[('drawing', 'Çizim'), ('specification', 'Şartname'), ('report', 'Rapor'), ('photo', 'Fotoğraf'), ('other', 'Diğer')], default='other', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Görev Tamamlama Dosyası',
                'verbose_name_plural': 'Görev Tamamlama Dosyaları',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='joborderdepartmenttask',
            options={'ordering': ['sequence'], 'verbose_name': 'Departman Görevi', 'verbose_name_plural': 'Departman Görevleri'},
        ),
        migrations.RenameIndex(
            model_name='joborderdepartmenttask',
            new_name='projects_jo_sales_o_b805d4_idx',
            old_name='projects_task_salesoffer_dept_idx',
        ),
        migrations.AddField(
            model_name='joborderdepartmenttaskfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_files', to='projects.joborderdepartmenttask'),
        ),
        migrations.AddField(
            model_name='joborderdepartmenttaskfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_task_files_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
