# Generated by Django 5.2.3 on 2026-03-05 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_joborderdepartmenttask_task_type'),
        ('sales', '0003_offer_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='source_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='sales.salesoffer'),
        ),
    ]
