# Generated by Django 5.2.3 on 2026-03-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_joborder_offer_files_remove_hierarchy_setup_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobordercostsummary',
            name='cost_not_applicable',
            field=models.BooleanField(default=False, help_text='When True, this job order is excluded from all department cost pending lists. Set by planning.'),
        ),
    ]
