# Generated by Django 5.2.3 on 2026-03-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_jobordercostsummary_cost_not_applicable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttasktemplateitem',
            name='task_type',
            field=models.CharField(blank=True, choices=[('cnc_cutting', 'CNC Kesim'), ('machining', 'Talaşlı İmalat'), ('welding', 'Kaynaklı İmalat'), ('painting', 'Boya'), ('part', 'Parça'), ('subcontracting', 'Taşeron')], help_text='Special task type — leave blank for regular tasks.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joborderdepartmenttask',
            name='task_type',
            field=models.CharField(blank=True, choices=[('cnc_cutting', 'CNC Kesim'), ('machining', 'Talaşlı İmalat'), ('welding', 'Kaynaklı İmalat'), ('painting', 'Boya'), ('part', 'Parça'), ('sales_consult', 'Satış Destek'), ('subcontracting', 'Taşeron')], db_index=True, help_text='Special task type — drives progress calculation and subcontracting logic. Leave blank for regular tasks.', max_length=20, null=True),
        ),
    ]
