# Generated by Django 5.2.3 on 2026-03-11 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_add_subcontracting_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborderdiscussiontopic',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topics', to='projects.joborder'),
        ),
        migrations.DeleteModel(
            name='DiscussionNotification',
        ),
    ]
