# Generated by Django 5.2.3 on 2026-03-24 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_add_on_update_cascade_joborder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joborderdiscussiontopic',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topic', to='projects.joborderdepartmenttask'),
        ),
        migrations.AlterField(
            model_name='joborderdiscussiontopic',
            name='job_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topics', to='projects.joborder'),
        ),
        migrations.AddIndex(
            model_name='joborderdiscussiontopic',
            index=models.Index(fields=['task', 'is_deleted'], name='projects_jo_task_id_d5c7be_idx'),
        ),
        migrations.AddConstraint(
            model_name='joborderdiscussiontopic',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('task__isnull', False)), fields=('task',), name='unique_active_topic_per_task'),
        ),
    ]
