# Generated by Django 5.2.3 on 2026-03-24 10:03

from django.db import migrations


def backfill_consult_topics(apps, schema_editor):
    JobOrderDepartmentTask = apps.get_model('projects', 'JobOrderDepartmentTask')
    JobOrderDiscussionTopic = apps.get_model('projects', 'JobOrderDiscussionTopic')

    tasks = JobOrderDepartmentTask.objects.filter(
        task_type='sales_consult',
    ).exclude(
        discussion_topic__is_deleted=False,
    )

    for task in tasks:
        JobOrderDiscussionTopic.objects.create(
            task=task,
            job_order=None,
            title=f'Danışmanlık: {task.title}',
            content='',
            topic_type='general',
            priority='normal',
            created_by=task.created_by,
        )


def reverse_backfill(apps, schema_editor):
    JobOrderDiscussionTopic = apps.get_model('projects', 'JobOrderDiscussionTopic')
    JobOrderDiscussionTopic.objects.filter(
        task__isnull=False,
        content='',
        title__startswith='Danışmanlık:',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_add_task_fk_to_discussion_topic'),
    ]

    operations = [
        migrations.RunPython(backfill_consult_topics, reverse_code=reverse_backfill),
    ]
