# Generated by Django 5.2.3 on 2026-03-31 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_backfill_missing_consult_discussion_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderTargetDateRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_date', models.DateField(blank=True, null=True)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_date_revisions_made', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_date_revisions', to='projects.joborder')),
            ],
            options={
                'verbose_name': 'Hedef Tarih Revizyonu',
                'verbose_name_plural': 'Hedef Tarih Revizyonları',
                'ordering': ['-changed_at'],
            },
        ),
    ]
