# Generated by Django 5.2.3 on 2026-04-02 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_jobordertargetdaterevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborderdepartmenttask',
            name='weight',
            field=models.PositiveIntegerField(default=10, help_text='Görev ağırlığı (minimum 1). Taşeron atamalarında allocated_weight_kg kullanılır.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
