# Generated by Django 5.2.3 on 2026-04-03 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_alter_joborderdepartmenttask_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delta_weight_kg', models.DecimalField(blank=True, decimal_places=4, help_text='total_weight_kg × (new_pct - old_pct) / 100; null when total_weight_kg is unset', max_digits=14, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='projects.joborder')),
            ],
            options={
                'verbose_name': 'İlerleme Kaydı',
                'verbose_name_plural': 'İlerleme Kayıtları',
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['job_order', 'logged_at'], name='projects_jo_job_ord_171e97_idx')],
            },
        ),
    ]
