# Generated by Django 5.2.3 on 2026-04-14 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_add_source_offer_item_to_joborder'),
        ('sales', '0011_add_shipping_price_to_salesoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='template_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='sales.offertemplatenode'),
        ),
    ]
