# Generated by Django 5.2.3 on 2026-04-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_add_template_node_to_joborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttasktemplateitem',
            name='task_type',
            field=models.CharField(blank=True, choices=[('cnc_cutting', 'CNC Kesim'), ('linear_cutting', 'Lineer Kesim'), ('machining', 'Talaşlı İmalat'), ('welding', 'Kaynaklı İmalat'), ('painting', 'Boya'), ('part', 'Parça'), ('subcontracting', 'Taşeron')], help_text='Special task type — leave blank for regular tasks.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joborderdepartmenttask',
            name='task_type',
            field=models.CharField(blank=True, choices=[('cnc_cutting', 'CNC Kesim'), ('linear_cutting', 'Lineer Kesim'), ('machining', 'Talaşlı İmalat'), ('welding', 'Kaynaklı İmalat'), ('painting', 'Boya'), ('part', 'Parça'), ('sales_consult', 'Satış Destek'), ('subcontracting', 'Taşeron')], db_index=True, help_text='Special task type — drives progress calculation and subcontracting logic. Leave blank for regular tasks.', max_length=20, null=True),
        ),
    ]
