# Generated by Django 5.2.3 on 2026-06-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_rename_customer_link_customer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_info',
            field=models.URLField(blank=True, help_text='Müşteri bilgi sayfası veya klasör bağlantısı (bildirimlerde kullanılır)', max_length=500, null=True),
        ),
    ]
