# Generated by Django 5.2.3 on 2026-07-06 08:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_backfill_customer_order_no_from_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborderprocurementline',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Unit price in EUR (6 decimal places so line totals can match external sheets exactly)', max_digits=16),
        ),
    ]
