# Generated by Django 5.2.3 on 2026-07-21 10:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_alter_joborderprocurementline_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobordercostsummary',
            name='machine_rental_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Completed crane/platform rental requests (EUR, completion-date FX)', max_digits=16),
        ),
    ]
