options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gemkom-backend-463510/gemkom-backend', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gemkom-backend-463510/gemkom-backend']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'gemkom-backend',
        '--image', 'gcr.io/gemkom-backend-463510/gemkom-backend',
        '--region', 'europe-west3',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/gemkom-backend-463510/gemkom-backend'
