steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gemkom-backend-463510/gemkom-backend', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gemkom-backend-463510/gemkom-backend']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker run --rm \
        -e DB_NAME=$_DB_NAME \
        -e DB_USER=$_DB_USER \
        -e DB_PASSWORD=$_DB_PASSWORD \
        -e DB_HOST=$_DB_HOST \
        -e DB_PORT=$_DB_PORT \
        -e SUPABASE_PROJECT_ID=$_SUPABASE_PROJECT_ID \
        -e SUPABASE_BUCKET_NAME=$_SUPABASE_BUCKET_NAME \
        -e SUPABASE_S3_ACCESS_KEY_ID=$_SUPABASE_S3_ACCESS_KEY_ID \
        -e SUPABASE_S3_SECRET_ACCESS_KEY=$_SUPABASE_S3_SECRET_ACCESS_KEY \
        -e SUPABASE_REGION=$_SUPABASE_REGION \
        gcr.io/gemkom-backend-463510/gemkom-backend \
        python manage.py migrate

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'gemkom-backend',
        '--image', 'gcr.io/gemkom-backend-463510/gemkom-backend',
        '--region', 'europe-west3',
        '--platform', 'managed',
        '--allow-unauthenticated',
      ]

images:
  - 'gcr.io/gemkom-backend-463510/gemkom-backend'
