# Generated by Django 5.2.3 on 2026-06-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_usergroup_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='organization_usergroup_slug_unique',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='slug',
            field=models.SlugField(blank=True, help_text="Machine-readable identifier (e.g. 'planning', 'management'). Auto-derived from name if left blank.", max_length=100, unique=True),
        ),
    ]
