# Generated by Django 5.2.3 on 2025-06-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='axis_w',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='axis_x',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='axis_y',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='axis_z',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='control_unit',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='drilling_tolerance',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='holder_type',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='is_cnc',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='production_year',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='rapid_traverse_speed',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='spindle_rpm',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='spindle_type',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='surface_tolerance',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='table_dimensions',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='table_load_capacity',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='tool_magazine_capacity',
        ),
        migrations.AddField(
            model_name='machine',
            name='name',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='properties',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('FTB', 'Zemin Tipi Manuel Borwerk'), ('TTB', 'Tabla Tipi Manuel Borwerk'), ('HM', 'Yatay İşleme Merkezi'), ('HT', 'Yatay Tornalama Merkezi'), ('VM', 'Dik İşleme Merkezi'), ('DM', 'Matkap'), ('SM', 'Kama Kanalı Açma Tezgahı'), ('BT', 'Köprü Tipi İşleme Merkezi'), ('ACT', 'AJAN Sac Kesim Tezgahı'), ('ECT', 'ESAB Sac Kesim Tezgahı')], max_length=10),
        ),
    ]
