# Generated by Django 5.2.3 on 2025-06-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_machine_axis_w_remove_machine_axis_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='used_in',
            field=models.CharField(default='machining', max_length=50),
        ),
    ]
