# Generated by Django 5.2.3 on 2025-06-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_machine_used_in'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
