# Generated by Django 5.2.3 on 2025-08-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_delete_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='freecurrencyapi', max_length=50)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('base', models.CharField(default='TRY', max_length=3)),
                ('rates', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
