# Generated by Django 5.2.3 on 2026-04-17 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0047_alter_departmenttasktemplateitem_task_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('hand_tool', 'Hand Tool'), ('power_tool', 'Power Tool'), ('instrument', 'Instrument'), ('consumable', 'Consumable'), ('other', 'Other')], default='other', max_length=20)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, default='Ambar', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='equipment_e_categor_590b96_idx'), models.Index(fields=['asset_type', 'is_active'], name='equipment_e_asset_t_fcdccd_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_checkins', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_checkouts', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_checkouts', to='projects.joborder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='equipment.equipmentitem')),
            ],
            options={
                'ordering': ['-checked_out_at'],
                'indexes': [models.Index(fields=['item', 'checked_in_at'], name='equipment_e_item_id_489a74_idx'), models.Index(fields=['checked_out_by', 'checked_in_at'], name='equipment_e_checked_2b7510_idx')],
            },
        ),
    ]
