# Generated by Django 5.2.3 on 2025-09-03 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted / Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('approved_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_entries', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='overtime.overtimerequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['start_at'], name='overtime_ov_start_a_1fb305_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['end_at'], name='overtime_ov_end_at_970458_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['status'], name='overtime_ov_status_3761df_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['requester'], name='overtime_ov_request_122397_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['team'], name='overtime_ov_team_7f4a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimeentry',
            index=models.Index(fields=['user'], name='overtime_ov_user_id_d0585b_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimeentry',
            index=models.Index(fields=['request', 'user'], name='overtime_ov_request_cc744b_idx'),
        ),
    ]
