# Generated by Django 5.2.3 on 2026-04-15 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0023_alter_machine_machine_type_alter_machine_used_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinearCuttingSession',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('material', models.CharField(help_text="Material / profile description, e.g. 'S235 IPE200'", max_length=100)),
                ('stock_length_mm', models.IntegerField(help_text='Standard stock bar length in mm, e.g. 6000')),
                ('kerf_mm', models.DecimalField(decimal_places=2, default=3, help_text='Saw blade kerf (material lost per cut) in mm', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('bars_needed', models.IntegerField(blank=True, null=True)),
                ('total_waste_mm', models.IntegerField(blank=True, null=True)),
                ('efficiency_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('optimization_result', models.JSONField(blank=True, help_text='Full optimization layout JSON for display without re-running', null=True)),
                ('tasks_created', models.BooleanField(default=False)),
                ('planning_request_created', models.BooleanField(default=False)),
                ('created_at', models.BigIntegerField(blank=True, help_text='Epoch ms', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linear_cutting_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinearCuttingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Part name / description', max_length=255)),
                ('job_no', models.CharField(blank=True, help_text='Optional job order number this part belongs to', max_length=255)),
                ('nominal_length_mm', models.IntegerField(help_text='Required cut length in mm')),
                ('quantity', models.IntegerField(help_text='Number of pieces needed')),
                ('angle_left_deg', models.DecimalField(decimal_places=2, default=0, help_text='Miter angle on the left end in degrees (0 = square cut)', max_digits=5)),
                ('angle_right_deg', models.DecimalField(decimal_places=2, default=0, help_text='Miter angle on the right end in degrees (0 = square cut)', max_digits=5)),
                ('profile_height_mm', models.IntegerField(default=0, help_text='Profile height in mm, used to calculate extra material consumed by angle cuts')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the UI')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='linear_cutting.linearcuttingsession')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LinearCuttingTask',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('completion_date', models.BigIntegerField(blank=True, null=True)),
                ('is_hold_task', models.BooleanField(default=False)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('finish_time', models.DateField(blank=True, null=True)),
                ('in_plan', models.BooleanField(db_index=True, default=False)),
                ('planned_start_ms', models.BigIntegerField(blank=True, null=True)),
                ('planned_end_ms', models.BigIntegerField(blank=True, null=True)),
                ('plan_order', models.IntegerField(blank=True, null=True)),
                ('plan_locked', models.BooleanField(default=False)),
                ('bar_index', models.PositiveIntegerField(help_text='Bar number within the session (1-based)')),
                ('stock_length_mm', models.IntegerField()),
                ('material', models.CharField(max_length=100)),
                ('layout_json', models.JSONField(help_text='Array of cuts on this bar: [{label, nominal_mm, effective_mm, offset_mm}]')),
                ('waste_mm', models.IntegerField(default=0)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('machine_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='machines.machine')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_tasks', to='linear_cutting.linearcuttingsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
