# Generated by Django 5.2.3 on 2026-04-16 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_cutting', '0001_initial'),
        ('procurement', '0035_purchaseorderline_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearcuttingsession',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Procurement catalog item for the raw stock bar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linear_cutting_sessions', to='procurement.item'),
        ),
    ]
