# Generated by Django 5.2.3 on 2026-04-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_cutting', '0002_linearcuttingsession_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linearcuttingsession',
            name='material',
            field=models.CharField(blank=True, help_text="Optional human-friendly label, e.g. 'S235 IPE200'. Falls back to item name if blank.", max_length=100),
        ),
    ]
