# Generated by Django 5.2.3 on 2026-04-16 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_cutting', '0003_alter_linearcuttingsession_material'),
        ('planning', '0009_planningrequestitem_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearcuttingsession',
            name='planning_request',
            field=models.OneToOneField(blank=True, help_text='Planning request created from this session via /confirm/', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linear_cutting_session', to='planning.planningrequest'),
        ),
    ]
