# Generated by Django 5.2.3 on 2026-04-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_cutting', '0004_linearcuttingsession_planning_request'),
        ('procurement', '0035_purchaseorderline_delivered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linearcuttingsession',
            name='bars_needed',
        ),
        migrations.RemoveField(
            model_name='linearcuttingsession',
            name='efficiency_pct',
        ),
        migrations.RemoveField(
            model_name='linearcuttingsession',
            name='item',
        ),
        migrations.RemoveField(
            model_name='linearcuttingsession',
            name='material',
        ),
        migrations.RemoveField(
            model_name='linearcuttingsession',
            name='total_waste_mm',
        ),
        migrations.AddField(
            model_name='linearcuttingpart',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Procurement catalog item for the stock bar this part is cut from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linear_cutting_parts', to='procurement.item'),
        ),
        migrations.AddField(
            model_name='linearcuttingpart',
            name='stock_length_mm',
            field=models.IntegerField(blank=True, help_text="Stock bar length override for this part's item group (mm). Uses session default if blank.", null=True),
        ),
        migrations.AddField(
            model_name='linearcuttingtask',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linear_cutting_tasks', to='procurement.item'),
        ),
        migrations.AlterField(
            model_name='linearcuttingsession',
            name='optimization_result',
            field=models.JSONField(blank=True, help_text='Per-item-group optimization layout JSON', null=True),
        ),
        migrations.AlterField(
            model_name='linearcuttingsession',
            name='stock_length_mm',
            field=models.IntegerField(help_text='Default stock bar length in mm (can be overridden per part). e.g. 6000'),
        ),
        migrations.AlterField(
            model_name='linearcuttingtask',
            name='bar_index',
            field=models.PositiveIntegerField(help_text='Global bar number within the session (1-based)'),
        ),
        migrations.AlterField(
            model_name='linearcuttingtask',
            name='material',
            field=models.CharField(help_text='Denormalized item name for display', max_length=100),
        ),
    ]
