# Generated by Django 5.2.3 on 2026-05-07 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_cutting', '0005_per_item_optimization'),
        ('procurement', '0035_purchaseorderline_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinearCuttingRemnantBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_mm', models.IntegerField(help_text='Actual available length of this piece in mm')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of identical pieces')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('consumed', 'Consumed')], default='available', max_length=20)),
                ('created_at', models.BigIntegerField(blank=True, help_text='Epoch ms', null=True)),
                ('consumed_at', models.BigIntegerField(blank=True, help_text='Epoch ms', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_remnant_bars', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remnant_bars', to='procurement.item')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remnant_bars', to='linear_cutting.linearcuttingsession')),
            ],
            options={
                'ordering': ['-length_mm'],
            },
        ),
    ]
