# Generated by Django 5.2.3 on 2026-05-12 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_cutting', '0008_stock_bar_usage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='linearcuttingstockbar',
            name='declared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_stock_bars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linearcuttingstockbar',
            name='length_mm',
            field=models.IntegerField(help_text='Length of this bar/piece in mm'),
        ),
        migrations.AlterField(
            model_name='linearcuttingstockbar',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Remaining pieces available'),
        ),
        migrations.AlterField(
            model_name='linearcuttingstockbarusage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
