# Generated by Django 5.2.3 on 2026-05-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_cutting', '0009_alter_linearcuttingstockbar_declared_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearcuttingpart',
            name='image_no',
            field=models.CharField(blank=True, help_text='Drawing / image reference number for this part', max_length=100),
        ),
    ]
