# Generated by Django 5.2.3 on 2026-07-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_cutting', '0010_linearcuttingpart_image_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearcuttingpart',
            name='allow_rotation',
            field=models.BooleanField(default=True, help_text='Optimizer may turn the piece 180° in the miter plane to share cuts. Disable for asymmetric profiles whose orientation matters.'),
        ),
        migrations.AddField(
            model_name='linearcuttingpart',
            name='requires_bending',
            field=models.BooleanField(default=False, help_text='Piece is bent after cutting; nominal_length_mm must then be the developed (flat/açınım) length.'),
        ),
        migrations.AddField(
            model_name='linearcuttingtask',
            name='is_remnant_bar',
            field=models.BooleanField(default=False, help_text='Bar was taken from remnant/warehouse stock (gets a lead trim cut)'),
        ),
        migrations.AddField(
            model_name='linearcuttingtask',
            name='passes_json',
            field=models.JSONField(blank=True, help_text='Ordered saw passes with operator stop distances (snapshot of geometry.passes_for_bar at confirm time)', null=True),
        ),
        migrations.AlterField(
            model_name='linearcuttingpart',
            name='angle_left_deg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Signed miter angle on the left end (0 = square; + = far corner cut back, - = near corner cut back). See linear_cutting/geometry.py', max_digits=5),
        ),
        migrations.AlterField(
            model_name='linearcuttingpart',
            name='angle_right_deg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Signed miter angle on the right end (0 = square cut)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='linearcuttingpart',
            name='nominal_length_mm',
            field=models.IntegerField(help_text='Long-point (bounding) length in mm — the piece measured at its longest'),
        ),
        migrations.AlterField(
            model_name='linearcuttingpart',
            name='profile_height_mm',
            field=models.IntegerField(default=0, help_text='Profile dimension (mm) in the miter plane; required for angled cuts'),
        ),
        migrations.AlterField(
            model_name='linearcuttingtask',
            name='layout_json',
            field=models.JSONField(help_text='Array of cuts on this bar: [{label, nominal_mm, offset_mm, angle_left_deg, angle_right_deg, flipped, shared_left, ...}]'),
        ),
    ]
