# Generated by Django 5.2.3 on 2026-07-21 10:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CraneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('basket_crane', 'Sepetli Vinç'), ('truck_crane', 'Kamyon Üstü Vinç'), ('mobile_crane', 'Mobil Vinç'), ('scissor_platform', 'Makaslı Platform'), ('articulated_platform', 'Eklemli Platform')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CraneRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('job_no', models.CharField(db_index=True, max_length=50)),
                ('pricing_option', models.CharField(choices=[('up_to_3h', '3 Saate Kadar'), ('up_to_8h', '8 Saate Kadar'), ('daily', 'Günlük')], max_length=10)),
                ('days', models.PositiveIntegerField(default=1)),
                ('needs_rigger', models.BooleanField(default=False)),
                ('needed_date', models.DateField(default=django.utils.timezone.localdate)),
                ('needed_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Acil'), ('critical', 'Kritik')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi'), ('completed', 'Tamamlandı')], default='submitted', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estimated_cost_currency', models.CharField(default='TRY', max_length=3)),
                ('estimate_breakdown', models.JSONField(blank=True, default=dict)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Fiili saat (vinç) veya gün (platform)', max_digits=8, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_cost_currency', models.CharField(default='TRY', max_length=3)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_crane_requests', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_crane_requests', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crane_requests', to=settings.AUTH_USER_MODEL)),
                ('crane_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='cranes.cranetype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department', 'status'], name='cranes_cran_departm_bdb19e_idx'), models.Index(fields=['status', 'created_at'], name='cranes_cran_status_873f2e_idx'), models.Index(fields=['job_no', 'status'], name='cranes_cran_job_no_6e849d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CraneRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(db_index=True)),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=3)),
                ('price_up_to_3h', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_up_to_8h', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transport_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rigger_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('crane_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='cranes.cranetype')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['crane_type', 'effective_from'], name='cranes_cran_crane_t_b7c770_idx')],
                'constraints': [models.UniqueConstraint(fields=('crane_type', 'effective_from'), name='uniq_crane_rate_effective_from')],
            },
        ),
    ]
