# Generated by Django 5.2.3 on 2025-11-18 11:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0025_remove_planningrequest_department_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(max_length=100)),
                ('needed_date', models.DateField(default=django.utils.timezone.now)),
                ('items', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Acil'), ('critical', 'Kritik')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('transferred', 'Planlamaya Aktarıldı'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_department_requests', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('needed_date', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Acil'), ('critical', 'Kritik')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('ready', 'Satın Almaya Hazır'), ('converted', 'Satın Almaya Aktarıldı'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_planning_requests', to=settings.AUTH_USER_MODEL)),
                ('department_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_requests', to='planning.departmentrequest')),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_requests', to='procurement.purchaserequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Acil'), ('critical', 'Kritik')], default='normal', max_length=20)),
                ('specifications', models.TextField(blank=True)),
                ('source_item_index', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_requests', to='procurement.item')),
                ('planning_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.planningrequest')),
            ],
            options={
                'ordering': ['planning_request', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='departmentrequest',
            index=models.Index(fields=['department', 'status'], name='planning_de_departm_7e4325_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentrequest',
            index=models.Index(fields=['status', 'created_at'], name='planning_de_status_caf78a_idx'),
        ),
        migrations.AddIndex(
            model_name='planningrequest',
            index=models.Index(fields=['status', 'created_at'], name='planning_pl_status_04fc79_idx'),
        ),
        migrations.AddIndex(
            model_name='planningrequest',
            index=models.Index(fields=['created_by', 'status'], name='planning_pl_created_533029_idx'),
        ),
    ]
