# Generated by Django 5.2.3 on 2025-11-18 12:05

import core.storages
import django.db.models.deletion
import planning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=core.storages.PrivateMediaStorage(), upload_to=planning.models.attachment_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Optional description of the file', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Optional description of the file', max_length=255)),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='planningrequest',
            name='planning_pl_status_04fc79_idx',
        ),
        migrations.RemoveIndex(
            model_name='planningrequest',
            name='planning_pl_created_533029_idx',
        ),
        migrations.AddField(
            model_name='fileasset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='planning.fileasset'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='source_attachment',
            field=models.ForeignKey(blank=True, help_text='Original attachment if this was mapped from another request/item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_attachments', to='planning.fileattachment'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['content_type', 'object_id'], name='planning_fi_content_cbacea_idx'),
        ),
    ]
