# Generated by Django 5.2.3 on 2025-11-19 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_fileasset_fileattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentrequest',
            name='needed_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
