# Generated by Django 5.2.3 on 2025-11-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_departmentrequest_needed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningrequest',
            name='purchase_request',
        ),
        migrations.AlterField(
            model_name='departmentrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('transferred', 'Satın Almaya Aktarıldı'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='planningrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('ready', 'Satın Almaya Hazır'), ('converted', 'Onaya Gönderildi'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20),
        ),
    ]
