# Generated by Django 5.2.3 on 2025-11-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_remove_planningrequest_purchase_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planningrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('ready', 'Satın Almaya Hazır'), ('converted', 'Onaya Gönderildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20),
        ),
    ]
