# Generated by Django 5.2.3 on 2025-11-25 12:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_planningrequest_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planningrequest',
            name='check_inventory',
            field=models.BooleanField(default=False, help_text='Whether to check and allocate from inventory'),
        ),
        migrations.AddField(
            model_name='planningrequest',
            name='fully_from_inventory',
            field=models.BooleanField(default=False, help_text='True if all items were fulfilled from inventory'),
        ),
        migrations.AddField(
            model_name='planningrequest',
            name='inventory_control_completed',
            field=models.BooleanField(default=False, help_text='True when inventory control process is completed'),
        ),
        migrations.AddField(
            model_name='planningrequestitem',
            name='quantity_from_inventory',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity allocated from inventory', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='planningrequestitem',
            name='quantity_to_purchase',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity that needs to be purchased', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='planningrequest',
            name='status',
            field=models.CharField(choices=[('pending_inventory', 'Stok Kontrolü Bekliyor'), ('ready', 'Satın Almaya Hazır'), ('converted', 'Onaya Gönderildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='ready', max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.DecimalField(decimal_places=2, help_text='Quantity allocated from inventory', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this allocation')),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_allocations', to=settings.AUTH_USER_MODEL)),
                ('planning_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_allocations', to='planning.planningrequestitem')),
            ],
            options={
                'ordering': ['-allocated_at'],
                'indexes': [models.Index(fields=['planning_request_item', 'allocated_at'], name='planning_in_plannin_dee2ee_idx')],
            },
        ),
    ]
