# Generated by Django 5.2.3 on 2025-12-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_planningrequestitem_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningrequest',
            name='erp_code',
            field=models.CharField(blank=True, help_text='ERP system code entered by planning team before marking ready for procurement', max_length=100),
        ),
        migrations.AlterField(
            model_name='planningrequest',
            name='status',
            field=models.CharField(choices=[('pending_inventory', 'Stok Kontrolü Bekliyor'), ('pending_erp_entry', 'ERP Girişi Bekliyor'), ('ready', 'Satın Almaya Hazır'), ('converted', 'Onaya Gönderildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='ready', max_length=20),
        ),
    ]
