# Generated by Django 5.2.3 on 2026-02-16 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_planningrequest_erp_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planningrequestitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningrequestitem',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_planning_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planningrequestitem',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
