# Generated by Django 5.2.3 on 2026-07-23 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_planningrequestitem_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planningrequestitem',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningrequestitem',
            name='consumed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_planning_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planningrequestitem',
            name='is_consumed',
            field=models.BooleanField(default=False),
        ),
    ]
