# Generated by Django 5.2.3 on 2025-06-20 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=255)),
                ('start_time', models.BigIntegerField()),
                ('finish_time', models.BigIntegerField(blank=True, null=True)),
                ('synced_to_jira', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('machine', models.CharField(blank=True, max_length=255, null=True)),
                ('job_no', models.CharField(blank=True, max_length=255, null=True)),
                ('image_no', models.CharField(blank=True, max_length=255, null=True)),
                ('position_no', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('manual_entry', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
