# Generated by Django 5.2.3 on 2025-07-03 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0002_timer_stopped_by_alter_timer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('job_no', models.CharField(blank=True, max_length=255, null=True)),
                ('image_no', models.CharField(blank=True, max_length=255, null=True)),
                ('position_no', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('completion_date', models.BigIntegerField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='timer',
            name='issue_key',
            field=models.ForeignKey(db_column='issue_key', on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='machining.task'),
        ),
    ]
