# Generated by Django 5.2.3 on 2025-07-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0004_populate_tasks_from_timers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='issue_key',
            field=models.CharField(max_length=255),
        ),
    ]
