# Generated by Django 5.2.3 on 2025-07-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0005_alter_timer_issue_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='image_no',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='job_no',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='position_no',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='quantity',
        ),
    ]
