# Generated by Django 5.2.3 on 2025-07-04 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_machinefault_resolved_by_and_more'),
        ('machining', '0006_remove_timer_image_no_remove_timer_job_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='machine_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_timers', to='machines.machine'),
        ),
    ]
