# Generated by Django 5.2.3 on 2025-07-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0007_timer_machine_fk'),
    ]

    operations = [
    ]
