# Generated by Django 5.2.3 on 2025-07-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0009_link_machine_foreign_keys_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_hold_task',
            field=models.BooleanField(default=False),
        ),
    ]
