# Generated by Django 5.2.3 on 2025-07-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0010_task_is_hold_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
