# Generated by Django 5.2.3 on 2025-07-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_machinefault_resolved_by_and_more'),
        ('machining', '0011_task_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finish_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='machine_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_tasks', to='machines.machine'),
        ),
    ]
