# Generated by Django 5.2.3 on 2025-07-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0012_task_finish_time_task_machine_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskKeyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='TI', max_length=10, unique=True)),
                ('current', models.IntegerField(default=0)),
            ],
        ),
    ]
