# Generated by Django 5.2.3 on 2025-08-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0013_taskkeycounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='synced_to_jira',
        ),
    ]
