# Generated by Django 5.2.3 on 2025-09-09 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0012_alter_machine_machine_type'),
        ('machining', '0014_remove_timer_synced_to_jira'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='plan_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='plan_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['machine_fk', 'planned_start_at'], name='machining_t_machine_fd2eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['machine_fk', 'plan_order'], name='machining_t_machine_3b6f02_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('plan_order__isnull', False)), fields=('machine_fk', 'plan_order'), name='uniq_machine_plan_order'),
        ),
    ]
