# Generated by Django 5.2.3 on 2025-09-09 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0012_alter_machine_machine_type'),
        ('machining', '0015_task_plan_locked_task_plan_order_task_planned_end_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='machining_t_machine_fd2eb1_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='planned_end_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='planned_start_at',
        ),
        migrations.AddField(
            model_name='task',
            name='planned_end_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_start_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='plan_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['machine_fk', 'planned_start_ms'], name='machining_t_machine_023ee6_idx'),
        ),
    ]
