# Generated by Django 5.2.3 on 2025-09-09 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0012_alter_machine_machine_type'),
        ('machining', '0016_remove_task_machining_t_machine_fd2eb1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='uniq_machine_plan_order',
        ),
        migrations.AddField(
            model_name='task',
            name='in_plan',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['machine_fk', 'in_plan'], name='machining_t_machine_c36356_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('in_plan', True), ('plan_order__isnull', False)), fields=('machine_fk', 'plan_order'), name='uniq_machine_plan_order_active'),
        ),
    ]
