# Generated by Django 5.2.3 on 2025-09-30 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0017_remove_task_uniq_machine_plan_order_task_in_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCostAgg',
            fields=[
                ('job_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('hours_ww', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_ah', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_su', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_ww', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_ah', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_su', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCostRecalcQueue',
            fields=[
                ('job_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('enqueued_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCostAggUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=100)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('hours_ww', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_ah', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_su', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_ww', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_ah', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_su', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job_no', 'user')},
            },
        ),
    ]
