# Generated by Django 5.2.3 on 2025-09-30 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0019_task_snapshots_step1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobcostagg',
            name='agg_jobno_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobcostagguser',
            name='agguser_jobno_idx',
        ),
        migrations.RemoveField(
            model_name='jobcostagg',
            name='job_no',
        ),
        migrations.AlterUniqueTogether(
            name='jobcostagguser',
            unique_together={('task', 'user')},
        ),
        migrations.RemoveField(
            model_name='jobcostrecalcqueue',
            name='job_no',
        ),
        migrations.AlterField(
            model_name='jobcostagg',
            name='job_no_cached',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobcostagg',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='machining.task'),
        ),
        migrations.AlterField(
            model_name='jobcostagguser',
            name='job_no_cached',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobcostagguser',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machining.task'),
        ),
        migrations.AlterField(
            model_name='jobcostrecalcqueue',
            name='task',
            field=models.OneToOneField(default=111, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='machining.task'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='jobcostagguser',
            name='job_no',
        ),
    ]
