# Generated by Django 5.2.3 on 2025-10-10 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0020_remove_machinefault_area_and_more'),
        ('machining', '0020_remove_jobcostagg_agg_jobno_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskKeyCounter',
        ),
        migrations.AlterField(
            model_name='task',
            name='machine_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='machines.machine'),
        ),
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
