# Generated by Django 5.2.3 on 2026-01-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0023_task_created_at_task_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobcostagguser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobcostagguser',
            name='task',
        ),
        migrations.RemoveField(
            model_name='jobcostagguser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobcostrecalcqueue',
            name='task',
        ),
        migrations.DeleteModel(
            name='JobCostAgg',
        ),
        migrations.DeleteModel(
            name='JobCostAggUser',
        ),
        migrations.DeleteModel(
            name='JobCostRecalcQueue',
        ),
    ]
