# Generated by Django 5.2.3 on 2026-02-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcreview',
            name='part_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
