# Generated by Django 5.2.3 on 2026-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0003_ncr_submission_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncr',
            name='status',
            field=models.CharField(choices=[('draft', 'Aksiyon Bekliyor'), ('submitted', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('closed', 'Kapatıldı')], db_index=True, default='draft', max_length=20),
        ),
    ]
