# Generated by Django 5.2.3 on 2026-03-10 07:28

import core.storages
import django.db.models.deletion
import quality_control.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0004_alter_ncr_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NCRFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=core.storages.PrivateMediaStorage(), upload_to=quality_control.models.ncr_file_upload_path)),
                ('file_type', models.CharField(choices=[('photo', 'Fotoğraf'), ('drawing', 'Çizim'), ('report', 'Rapor'), ('specification', 'Şartname'), ('other', 'Diğer')], default='other', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ncr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='quality_control.ncr')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncr_files_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NCR Dosyası',
                'verbose_name_plural': 'NCR Dosyaları',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
