# Generated by Django 5.2.3 on 2026-03-23 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0038_add_on_update_cascade_joborder'),
        ('quality_control', '0006_ncr_assigned_team_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ncr',
            name='quality_con_assigne_b896fb_idx',
        ),
        migrations.AddIndex(
            model_name='ncr',
            index=models.Index(fields=['assigned_team_id', 'status'], name='quality_con_assigne_b5d8a2_idx'),
        ),
    ]
