# Generated by Django 5.2.3 on 2026-05-12 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_seed_positions_and_permissions'),
        ('projects', '0048_alter_departmenttasktemplateitem_task_type_and_more'),
        ('quality_control', '0010_ncr_assigned_team_to_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ncr',
            name='quality_con_assigne_b5d8a2_idx',
        ),
        migrations.AddIndex(
            model_name='ncr',
            index=models.Index(fields=['assigned_team', 'status'], name='quality_con_assigne_b5d8a2_idx'),
        ),
    ]
