# Generated by Django 5.2.3 on 2026-07-02 13:29

import core.storages
import django.db.models.deletion
import quality_control.models
from django.conf import settings
from django.db import migrations, models


# Mirror the dynamic lock-down in core/0006 for this new public table:
# enable RLS and revoke anon/authenticated privileges (the Django app connects
# as the table owner, so this only affects the Supabase anon/authenticated roles).
LOCK_DOWN_SQL = """
DO $$
BEGIN
    EXECUTE 'ALTER TABLE public.quality_control_qualitydocument ENABLE ROW LEVEL SECURITY';
    IF to_regrole('anon') IS NOT NULL THEN
        EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE public.quality_control_qualitydocument FROM anon';
    END IF;
    IF to_regrole('authenticated') IS NOT NULL THEN
        EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE public.quality_control_qualitydocument FROM authenticated';
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_remove_customer_customer_info'),
        ('quality_control', '0014_ncr_assigned_team_to_usergroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('procedure', 'Prosedür'), ('instruction', 'Talimat'), ('form', 'Form'), ('certificate', 'Sertifika'), ('material_cert', 'Malzeme Sertifikası'), ('inspection_plan', 'Kontrol Planı'), ('inspection_report', 'Muayene Raporu'), ('test_report', 'Test Raporu'), ('wps', 'Kaynak Prosedürü (WPS)'), ('drawing', 'Çizim'), ('other', 'Diğer')], db_index=True, default='other', max_length=30)),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('revision', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(storage=core.storages.PrivateMediaStorage(), upload_to=quality_control.models.quality_document_upload_path)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_documents', to='projects.joborder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kalite Evrağı',
                'verbose_name_plural': 'Kalite Evrakları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type', 'is_active'], name='quality_con_documen_a73c3c_idx'), models.Index(fields=['job_order', 'is_active'], name='quality_con_job_ord_45eef7_idx')],
            },
        ),
        migrations.RunSQL(
            sql=LOCK_DOWN_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
