# Generated by Django 5.2.3 on 2026-01-15 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', 'populate_downtime_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
