# Generated by Django 5.2.3 on 2026-04-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_alter_timer_content_type_alter_timer_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='tools',
        ),
        migrations.DeleteModel(
            name='OperationTool',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
