# Generated by Django 5.2.3 on 2025-12-16 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('machines', '0021_alter_machine_machine_type'),
        ('tasks', '0003_taskfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timer',
            constraint=models.UniqueConstraint(condition=models.Q(('finish_time__isnull', True)), fields=('user', 'machine_fk', 'content_type', 'object_id'), name='unique_active_timer_per_user_machine_task'),
        ),
    ]
