# Generated by Django 5.2.3 on 2025-12-30 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0021_alter_machine_machine_type'),
        ('tasks', '0004_timer_unique_active_timer_per_user_machine_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_no', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('image_no', models.CharField(blank=True, max_length=255, null=True)),
                ('position_no', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('finish_time', models.DateField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('completion_date', models.BigIntegerField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('completion_date', models.BigIntegerField(blank=True, null=True)),
                ('is_hold_task', models.BooleanField(default=False)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('finish_time', models.DateField(blank=True, null=True)),
                ('in_plan', models.BooleanField(db_index=True, default=False)),
                ('planned_start_ms', models.BigIntegerField(blank=True, null=True)),
                ('planned_end_ms', models.BigIntegerField(blank=True, null=True)),
                ('plan_order', models.IntegerField(blank=True, null=True)),
                ('plan_locked', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('interchangeable', models.BooleanField(default=False, help_text='If True, this operation can be completed out of order')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('machine_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='machines.machine')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='tasks.part')),
            ],
            options={
                'ordering': ['part', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='tasks_tool_categor_1ddc1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperationTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_tools', to='tasks.operation')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_operations', to='tasks.tool')),
            ],
            options={
                'ordering': ['operation', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='operations', through='tasks.OperationTool', to='tasks.tool'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['job_no'], name='tasks_part_job_no_75235b_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['completion_date'], name='tasks_part_complet_62ef44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operationtool',
            unique_together={('operation', 'tool')},
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['part', 'order'], name='tasks_opera_part_id_dfc623_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['machine_fk', 'in_plan'], name='tasks_opera_machine_9285df_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['machine_fk', 'plan_order'], name='tasks_opera_machine_a5a7a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('part', 'order'), name='unique_operation_order_per_part'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(condition=models.Q(('in_plan', True), ('plan_order__isnull', False)), fields=('machine_fk', 'plan_order'), name='unique_operation_plan_order'),
        ),
    ]
