# Generated by Django 5.2.3 on 2026-01-07 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_part_operation_tool_operationtool_operation_tools_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCostRecalcQueue',
            fields=[
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tasks.part')),
                ('enqueued_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Part Cost Recalc Queue',
                'verbose_name_plural': 'Part Cost Recalc Queue',
                'db_table': 'tasks_partcostrecalcqueue',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='task_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PartCostAgg',
            fields=[
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cost_agg', serialize=False, to='tasks.part')),
                ('job_no_cached', models.CharField(db_index=True, help_text='Cached job_no for filtering', max_length=100)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('hours_ww', models.DecimalField(decimal_places=2, default=0, help_text='Working hours', max_digits=12)),
                ('hours_ah', models.DecimalField(decimal_places=2, default=0, help_text='After hours', max_digits=12)),
                ('hours_su', models.DecimalField(decimal_places=2, default=0, help_text='Sunday hours', max_digits=12)),
                ('cost_ww', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_ah', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_su', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Part Cost Aggregate',
                'verbose_name_plural': 'Part Cost Aggregates',
                'db_table': 'tasks_partcostagg',
                'indexes': [models.Index(fields=['job_no_cached'], name='tasks_partc_job_no__b5ca73_idx'), models.Index(fields=['-total_cost'], name='tasks_partc_total_c_909415_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartCostAggUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no_cached', models.CharField(db_index=True, max_length=100)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('hours_ww', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_ah', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_su', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_ww', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_ah', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_su', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_agg_users', to='tasks.part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Part Cost Per User',
                'verbose_name_plural': 'Part Costs Per User',
                'db_table': 'tasks_partcostaguser',
                'indexes': [models.Index(fields=['user'], name='tasks_partc_user_id_b33703_idx'), models.Index(fields=['job_no_cached'], name='tasks_partc_job_no__8e17b5_idx')],
                'unique_together': {('part', 'user')},
            },
        ),
    ]
