# Generated by Django 5.2.3 on 2026-01-09 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0022_machinefault_downtime_end_ms_and_more'),
        ('tasks', '0006_partcostrecalcqueue_part_task_key_partcostagg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='related_fault',
            field=models.ForeignKey(blank=True, help_text='Machine fault that caused this downtime', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_timers', to='machines.machinefault'),
        ),
        migrations.AddField(
            model_name='timer',
            name='timer_type',
            field=models.CharField(choices=[('productive', 'Productive Work'), ('break', 'Break/Lunch'), ('downtime', 'Downtime')], db_index=True, default='productive', help_text='Type of time being tracked', max_length=20),
        ),
        migrations.CreateModel(
            name='DowntimeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('break', 'Break/Lunch'), ('downtime', 'Downtime/Waiting'), ('complete', 'Work Complete')], max_length=20)),
                ('creates_timer', models.BooleanField(default=True, help_text='If True, selecting this reason automatically starts a new timer with this reason')),
                ('requires_fault_reference', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='tasks_downt_categor_3b8ffe_idx')],
            },
        ),
        migrations.AddField(
            model_name='timer',
            name='downtime_reason',
            field=models.ForeignKey(blank=True, help_text='Reason for non-productive time', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timers', to='tasks.downtimereason'),
        ),
    ]
