# Generated by Django 5.2.3 on 2026-07-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_tool_operationtool'),
        ('tasks', '0008_part_department_request'),
    ]

    operations = [
    ]
