# Generated by Django 5.2.3 on 2025-12-23 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeldingTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(db_index=True, help_text="Job number (e.g., '001-23'). Indexed for fast partial searches.", max_length=100)),
                ('date', models.DateField(db_index=True, help_text='The date when the work was performed')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Number of hours worked (e.g., 2.5 for 2 hours 30 minutes)', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Optional notes about the work performed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_welding_entries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='The welding employee who worked on this job', on_delete=django.db.models.deletion.CASCADE, related_name='welding_time_entries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_welding_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Welding Time Entry',
                'verbose_name_plural': 'Welding Time Entries',
                'db_table': 'welding_time_entry',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='welding_tim_employe_fcafbc_idx'), models.Index(fields=['job_no', 'date'], name='welding_tim_job_no_5ea38e_idx'), models.Index(fields=['date'], name='welding_tim_date_526017_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'job_no', 'date'), name='unique_welding_time_entry_per_employee_job_date')],
            },
        ),
    ]
