# Generated by Django 5.2.3 on 2025-12-23 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weldingtimeentry',
            name='unique_welding_time_entry_per_employee_job_date',
        ),
        migrations.AddField(
            model_name='weldingtimeentry',
            name='overtime_type',
            field=models.CharField(choices=[('regular', 'Regular Hours'), ('after_hours', 'After Hours / Saturday (1.5x)'), ('holiday', 'Holiday / Sunday (2x)')], db_index=True, default='regular', help_text='Type of work hours: regular, after_hours (1.5x), or holiday (2x)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='weldingtimeentry',
            index=models.Index(fields=['overtime_type'], name='welding_tim_overtim_84aecc_idx'),
        ),
        migrations.AddConstraint(
            model_name='weldingtimeentry',
            constraint=models.UniqueConstraint(fields=('employee', 'job_no', 'date', 'overtime_type'), name='unique_welding_entry_per_employee_job_date_overtime'),
        ),
    ]
