# Generated by Django 5.2.3 on 2025-12-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0002_remove_weldingtimeentry_unique_welding_time_entry_per_employee_job_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weldingtimeentry',
            name='unique_welding_entry_per_employee_job_date_overtime',
        ),
    ]
