# Generated by Django 5.2.3 on 2025-12-24 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0003_remove_weldingtimeentry_unique_welding_entry_per_employee_job_date_overtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeldingJobCostAgg',
            fields=[
                ('job_no', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('hours_regular', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_after_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_holiday', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_regular', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_after_hours', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_holiday', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Welding Job Cost Aggregate',
                'verbose_name_plural': 'Welding Job Cost Aggregates',
                'db_table': 'welding_job_cost_agg',
            },
        ),
        migrations.CreateModel(
            name='WeldingJobCostRecalcQueue',
            fields=[
                ('job_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('enqueued_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Welding Job Cost Recalc Queue',
                'verbose_name_plural': 'Welding Job Cost Recalc Queue',
                'db_table': 'welding_job_cost_recalc_queue',
            },
        ),
        migrations.CreateModel(
            name='WeldingJobCostAggUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(db_index=True, max_length=100)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('hours_regular', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_after_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_holiday', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_regular', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_after_hours', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_holiday', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Welding Job Cost Aggregate (User)',
                'verbose_name_plural': 'Welding Job Cost Aggregates (User)',
                'db_table': 'welding_job_cost_agg_user',
                'unique_together': {('job_no', 'user')},
            },
        ),
    ]
