# Generated by Django 5.2.3 on 2026-04-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0004_weldingjobcostagg_weldingjobcostrecalcqueue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weldingtimeentry',
            name='deduct_from_subcontractor',
            field=models.BooleanField(default=False, help_text='If true, this time entry will be deducted from the subcontractor'),
        ),
    ]
