# Generated by Django 5.2.3 on 2026-05-04 08:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_alter_departmenttasktemplateitem_task_type_and_more'),
        ('teams', '0001_initial'),
        ('welding', '0005_add_deduct_from_subcontractor_to_weldingtimeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_weight_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_team_assignment', to='projects.joborderdepartmenttask')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='teams.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dahili Takım Ataması',
                'verbose_name_plural': 'Dahili Takım Atamaları',
                'db_table': 'welding_internal_team_assignment',
            },
        ),
    ]
