# Generated by Django 5.2.3 on 2026-07-16 10:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_alter_joborderprocurementline_unit_price'),
        ('subcontracting', '0011_add_tier_type_to_price_tier'),
        ('teams', '0001_initial'),
        ('welding', '0006_internalteamassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeldingPlanAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_weight_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welding_plan_allocations', to='projects.joborderdepartmenttask')),
                ('promoted_internal_team_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_plan_allocation', to='welding.internalteamassignment')),
                ('promoted_subcontracting_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_plan_allocation', to='subcontracting.subcontractingassignment')),
                ('subcontractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='welding_plan_allocations', to='subcontracting.subcontractor')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='welding_plan_allocations', to='teams.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kaynak Plan Tahsisi',
                'verbose_name_plural': 'Kaynak Plan Tahsisleri',
                'db_table': 'welding_plan_allocation',
                'indexes': [models.Index(fields=['department_task'], name='welding_pla_departm_25fb17_idx'), models.Index(fields=['subcontractor'], name='welding_pla_subcont_12ed01_idx'), models.Index(fields=['team'], name='welding_pla_team_id_072716_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('subcontractor__isnull', False), ('team__isnull', True)), models.Q(('subcontractor__isnull', True), ('team__isnull', False)), _connector='OR'), name='welding_plan_alloc_exactly_one_resource')],
            },
        ),
    ]
