# Generated by Django 5.2.3 on 2025-10-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0020_remove_machinefault_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CncTask',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('completion_date', models.BigIntegerField(blank=True, null=True)),
                ('is_hold_task', models.BooleanField(default=False)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('finish_time', models.DateField(blank=True, null=True)),
                ('in_plan', models.BooleanField(db_index=True, default=False)),
                ('planned_start_ms', models.BigIntegerField(blank=True, null=True)),
                ('planned_end_ms', models.BigIntegerField(blank=True, null=True)),
                ('plan_order', models.IntegerField(blank=True, null=True)),
                ('plan_locked', models.BooleanField(default=False)),
                ('nesting_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('machine_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='machines.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
