# Generated by Django 5.2.3 on 2025-10-10 13:34
import core.storages
from django.db import migrations, models

import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnctask',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cnctask',
            name='nesting_pdf',
            field=models.FileField(blank=True, null=True, storage=core.storages.PrivateMediaStorage(), upload_to=tasks.models.task_attachment_upload_path, verbose_name='Nesting PDF'),
        ),
    ]
