# Generated by Django 5.2.3 on 2025-10-11 11:33

import cnc_cutting.models
import core.storages
from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0002_cnctask_dimensions_cnctask_nesting_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnctask',
            name='nesting_pdf',
        ),
        migrations.AddField(
            model_name='cnctask',
            name='nesting_file',
            field=models.FileField(blank=True, null=True, storage=core.storages.PrivateMediaStorage(), upload_to=tasks.models.task_attachment_upload_path, verbose_name='Nesting File'),
        ),
    ]
