# Generated by Django 5.2.3 on 2025-10-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0003_remove_cnctask_nesting_pdf_cnctask_nesting_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CncPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(db_index=True, max_length=255)),
                ('image_no', models.CharField(blank=True, max_length=255, null=True)),
                ('position_no', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Weight of the single part in kg.', max_digits=10, null=True)),
                ('cnc_task', models.ForeignKey(help_text='The nesting task this part belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='cnc_cutting.cnctask')),
            ],
        ),
    ]
