# Generated by Django 5.2.3 on 2025-10-11 18:59

import core.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0004_cncpart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnctask',
            name='nesting_file',
        ),
        migrations.CreateModel(
            name='CncTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=core.storages.PrivateMediaStorage(), upload_to=tasks.models.task_attachment_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cnc_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cnc_cutting.cnctask')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
