# Generated by Django 5.2.3 on 2025-10-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0005_remove_cnctask_nesting_file_cnctaskfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CncTaskFile',
        ),
    ]
