# Generated by Django 5.2.3 on 2025-10-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0006_delete_cnctaskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnctask',
            name='processed_by_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
