# Generated by Django 5.2.3 on 2025-10-30 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0007_cnctask_processed_by_warehouse'),
        ('machines', '0021_alter_machine_machine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnctask',
            name='processed_warehouse_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cnctask',
            name='machine_fk',
            field=models.ForeignKey(blank=True, help_text='The CNC machine assigned to this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnc_tasks', to='machines.machine'),
        ),
    ]
