# Generated by Django 5.2.3 on 2025-11-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0009_remnantplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remnantplate',
            name='thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
