# Generated by Django 5.2.3 on 2025-11-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0010_alter_remnantplate_thickness_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnctask',
            name='heat_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='remnantplate',
            name='heat_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
