# Generated by Django 5.2.3 on 2025-11-04 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0011_cnctask_heat_number_remnantplate_heat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remnantplate',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='cnctask',
            name='selected_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnc_tasks', to='cnc_cutting.remnantplate'),
        ),
    ]
