# Generated by Django 5.2.3 on 2025-11-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0012_remove_remnantplate_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cncpart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
