# Generated by Django 5.2.3 on 2025-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0013_cncpart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnctask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
