# Generated by Django 5.2.3 on 2025-12-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0015_cnctask_created_at_cnctask_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remnantplate',
            name='thickness_mm_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
