# Generated by Django 5.2.3 on 2026-01-09 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0016_remnantplate_thickness_mm_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnctask',
            name='selected_plate',
        ),
        migrations.CreateModel(
            name='RemnantPlateUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField(default=1, help_text='Number of plates used from the remnant plate')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('cnc_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_usage_records', to='cnc_cutting.cnctask')),
                ('remnant_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='cnc_cutting.remnantplate')),
            ],
            options={
                'unique_together': {('cnc_task', 'remnant_plate')},
            },
        ),
        migrations.AddField(
            model_name='cnctask',
            name='remnant_plates',
            field=models.ManyToManyField(blank=True, related_name='cnc_tasks', through='cnc_cutting.RemnantPlateUsage', to='cnc_cutting.remnantplate'),
        ),
    ]
