# Generated by Django 5.2.3 on 2026-07-23 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_cutting', '0017_remove_cnctask_selected_plate_remnantplateusage_and_more'),
        ('planning', '0010_planningrequestitem_consumed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnctask',
            name='planning_request_item',
            field=models.ForeignKey(blank=True, help_text='Plate stock line (item code 0100/0101) this cut consumes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnc_tasks', to='planning.planningrequestitem'),
        ),
    ]
