# Generated by Django 5.2.3 on 2025-08-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='department',
        ),
    ]
