# Generated by Django 5.2.3 on 2025-08-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_remove_purchaserequest_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieroffer',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='supplieroffer',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offers', to='procurement.paymenttype'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='draft', max_length=20),
        ),
    ]
