# Generated by Django 5.2.3 on 2025-08-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_remove_supplieroffer_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='job_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
