# Generated by Django 5.2.3 on 2025-08-20 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_purchaserequestitem_job_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('awaiting_invoice', 'Awaiting Invoice'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='awaiting_invoice', max_length=20)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.purchaserequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplier')),
                ('supplier_offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplieroffer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('item_offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='procurement.itemoffer')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorder')),
                ('purchase_request_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.purchaserequestitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
