# Generated by Django 5.2.3 on 2025-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_purchaserequest_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('awaiting_invoice', 'Proforma Bekliyor'), ('awaiting_payment', 'Ödeme Bekliyor'), ('paid', 'Ödendi'), ('cancelled', 'Cancelled')], default='awaiting_invoice', max_length=20),
        ),
    ]
