# Generated by Django 5.2.3 on 2025-08-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='currency',
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='currency',
            field=models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini')], default='TRY', max_length=3),
        ),
    ]
