# Generated by Django 5.2.3 on 2025-08-20 19:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_remove_supplier_currency_supplieroffer_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('default_lines', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='default_payment_method',
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='procurement.paymentterms'),
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('basis', models.CharField(choices=[('immediate', 'Peşin'), ('on_delivery', 'Teslim Edildiğinde'), ('after_invoice', 'Fatura Kesildikten Sonra'), ('after_delivery', 'Teslimden Sonra'), ('custom', 'Diğer')], default='custom', max_length=20)),
                ('offset_days', models.IntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_schedules', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='procurement.purchaseorder')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='procurement.paymentterms')),
            ],
            options={
                'ordering': ['purchase_order', 'sequence'],
                'unique_together': {('purchase_order', 'sequence')},
            },
        ),
    ]
