# Generated by Django 5.2.3 on 2025-08-20 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_paymentterms_remove_supplier_default_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieroffer',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offers', to='procurement.paymentterms'),
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
