# Generated by Django 5.2.3 on 2025-08-21 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_seed_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='needed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
