# Generated by Django 5.2.3 on 2025-08-21 11:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_purchaserequest_needed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequestitem',
            name='job_no',
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='procurement.purchaseorderline')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['job_no'], name='procurement_job_no_559403_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='procurement.purchaserequestitem')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('purchase_request_item', 'job_no')},
            },
        ),
    ]
