# Generated by Django 5.2.3 on 2025-08-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_paymentschedule_paid_with_tax_purchaseorder_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Ödeme Bekliyor'), ('paid', 'Ödendi'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=20),
        ),
    ]
