# Generated by Django 5.2.3 on 2025-08-25 07:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_alter_purchaseorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi')], default='submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseRequestDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('needed_date', models.DateField(default=datetime.datetime(2025, 8, 25, 7, 58, 48, 771129, tzinfo=datetime.timezone.utc))),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Acil'), ('critical', 'Kritik')], default='normal', max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['requestor'], name='procurement_request_bd2125_idx')],
            },
        ),
    ]
