# Generated by Django 5.2.3 on 2025-08-25 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0016_alter_purchaserequest_status_purchaserequestdraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestdraft',
            name='needed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
