# Generated by Django 5.2.3 on 2025-08-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0017_alter_purchaserequestdraft_needed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='is_rolling_mill',
            field=models.BooleanField(default=False),
        ),
    ]
