# Generated by Django 5.2.3 on 2025-08-27 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_purchaserequest_is_rolling_mill'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='dbs_agreement_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='dbs_bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='dbs_currency',
            field=models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini')], default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='supplier',
            name='dbs_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='dbs_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='dbs_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='has_dbs',
            field=models.BooleanField(default=False),
        ),
    ]
