# Generated by Django 5.2.3 on 2025-08-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_supplier_address_supplier_bank_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
