# Generated by Django 5.2.3 on 2025-09-18 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_supplier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='dbs_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
