# Generated by Django 5.2.3 on 2025-09-18 18:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0021_supplier_dbs_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='dbs_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
