# Generated by Django 5.2.3 on 2025-11-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0024_alter_departmentrequest_status_planningrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningrequest',
            name='department_request',
        ),
        migrations.RemoveField(
            model_name='planningrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='planningrequest',
            name='purchase_request',
        ),
        migrations.RemoveField(
            model_name='planningrequestitem',
            name='planning_request',
        ),
        migrations.RemoveField(
            model_name='planningrequestitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='DepartmentRequest',
        ),
        migrations.DeleteModel(
            name='PlanningRequest',
        ),
        migrations.DeleteModel(
            name='PlanningRequestItem',
        ),
    ]
