# Generated by Django 5.2.3 on 2025-11-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_remove_planningrequest_purchase_request_and_more'),
        ('procurement', '0025_remove_planningrequest_department_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='planning_requests',
            field=models.ManyToManyField(blank=True, related_name='purchase_requests', to='planning.planningrequest'),
        ),
    ]
