# Generated by Django 5.2.3 on 2025-11-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_planningrequest_completed_at_and_more'),
        ('procurement', '0026_purchaserequest_planning_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='planning_requests',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='planning_request_items',
            field=models.ManyToManyField(blank=True, related_name='purchase_requests', to='planning.planningrequestitem'),
        ),
    ]
