# Generated by Django 5.2.3 on 2025-11-25 12:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0027_remove_purchaserequest_planning_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current available stock quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
