# Generated by Django 5.2.3 on 2025-11-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0028_item_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('stock', 'Stok'), ('expenditure', 'Masraf'), ('subcontracting', 'Alt Yüklenici')], default='stock', help_text='Type of item: stock, expenditure, or subcontracting', max_length=20),
        ),
    ]
