# Generated by Django 5.2.3 on 2025-11-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0029_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='item_description',
            field=models.CharField(blank=True, help_text="Original item name/description from department request (e.g., 'Bearing X123 for Machine Y')", max_length=500),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='item_description',
            field=models.CharField(blank=True, help_text="Original item name/description from department request (e.g., 'Bearing X123 for Machine Y')", max_length=500),
        ),
    ]
