# Generated by Django 5.2.3 on 2025-12-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0030_purchaseorderline_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('adet', 'Adet'), ('kg', 'KG'), ('metre', 'Metre'), ('litre', 'Litre'), ('paket', 'Paket'), ('kutu', 'Kutu'), ('set', 'Takım')], max_length=20),
        ),
    ]
