# Generated by Django 5.2.3 on 2025-12-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0031_alter_item_code_alter_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('adet', 'Adet'), ('kg', 'KG'), ('metre', 'Metre'), ('litre', 'Litre'), ('paket', 'Paket'), ('kutu', 'Kutu'), ('set', 'Takım'), ('m2', 'Metrekare'), ('varil', 'Varil')], max_length=20),
        ),
    ]
