# Generated by Django 5.2.3 on 2026-01-30 11:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_planningrequest_erp_code_and_more'),
        ('procurement', '0032_alter_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Birim ağırlığı (ilerleme hesaplaması için)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='planning_request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_items', to='planning.planningrequestitem'),
        ),
    ]
