# Generated by Django 5.2.3 on 2026-02-12 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0033_item_unit_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='purchase_request_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='procurement.purchaserequestitem'),
        ),
    ]
