# Generated by Django 5.2.3 on 2025-08-18 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('procurement', '0004_purchaserequestitem_job_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_amount_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_amount_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('priority_in', models.JSONField(blank=True, default=list)),
                ('selection_priority', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='PRApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_stage_order', models.PositiveIntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approvals.approvalpolicy')),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='procurement.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='PRApprovalStageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('required_approvals', models.PositiveIntegerField(default=1)),
                ('approver_user_ids', models.JSONField(blank=True, default=list)),
                ('approver_group_ids', models.JSONField(blank=True, default=list)),
                ('approved_count', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_instances', to='approvals.prapprovalworkflow')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('required_approvals', models.PositiveIntegerField(default=1)),
                ('approver_groups', models.ManyToManyField(blank=True, related_name='approval_stages', to='auth.group')),
                ('approver_users', models.ManyToManyField(blank=True, related_name='approval_stages', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='approvals.approvalpolicy')),
            ],
            options={
                'ordering': ['policy', 'order'],
                'unique_together': {('policy', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PRApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.prapprovalstageinstance')),
            ],
            options={
                'ordering': ['decided_at'],
                'unique_together': {('stage_instance', 'approver')},
            },
        ),
    ]
