# Generated by Django 5.2.3 on 2025-08-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_seed_default_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='prapprovalworkflow',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
