# Generated by Django 5.2.3 on 2025-08-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_prapprovalworkflow_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalpolicy',
            name='is_rolling_mill',
            field=models.BooleanField(default=False),
        ),
    ]
