# Generated by Django 5.2.3 on 2025-09-02 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_approvalpolicy_is_rolling_mill'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_stage_order', models.PositiveIntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approvals.approvalpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('required_approvals', models.PositiveIntegerField(default=1)),
                ('approver_user_ids', models.JSONField(blank=True, default=list)),
                ('approver_group_ids', models.JSONField(blank=True, default=list)),
                ('approved_count', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_instances', to='approvals.approvalworkflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.approvalstageinstance')),
            ],
            options={
                'ordering': ['decided_at'],
                'unique_together': {('stage_instance', 'approver')},
            },
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['content_type', 'object_id'], name='approvals_a_content_d1e647_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstageinstance',
            unique_together={('workflow', 'order')},
        ),
    ]
