# Generated by Django 5.2.3 on 2025-09-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_approvalworkflow_approvalstageinstance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prapprovalstageinstance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prapprovalstageinstance',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='prapprovalworkflow',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='prapprovalworkflow',
            name='purchase_request',
        ),
        migrations.DeleteModel(
            name='PRApprovalDecision',
        ),
        migrations.DeleteModel(
            name='PRApprovalStageInstance',
        ),
        migrations.DeleteModel(
            name='PRApprovalWorkflow',
        ),
    ]
