# Generated by Django 5.2.3 on 2026-03-11 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('pr_approval_requested', 'Satınalma Onayı Bekleniyor'), ('pr_approved', 'Satınalma Talebi Onaylandı'), ('pr_rejected', 'Satınalma Talebi Reddedildi'), ('pr_po_created', 'Satınalma Siparişi Oluşturuldu'), ('ot_approval_requested', 'Mesai Onayı Bekleniyor'), ('ot_approved', 'Mesai Talebi Onaylandı'), ('ot_rejected', 'Mesai Talebi Reddedildi'), ('qc_review_submitted', 'KK İncelemesi Gönderildi'), ('qc_review_approved', 'KK İncelemesi Onaylandı'), ('qc_review_rejected', 'KK İncelemesi Reddedildi'), ('ncr_created', 'NCR Oluşturuldu'), ('ncr_submitted', 'NCR Onaya Gönderildi'), ('ncr_approved', 'NCR Onaylandı'), ('ncr_rejected', 'NCR Reddedildi'), ('ncr_assigned', 'NCR Atandı'), ('sales_approval_requested', 'Satış Teklifi Onay Bekliyor'), ('sales_approved', 'Satış Teklifi Onaylandı'), ('sales_rejected', 'Satış Teklifi Reddedildi'), ('sales_consultation', 'Satış Danışma Talebi'), ('sales_converted', 'Teklif İş Emrine Dönüştürüldü'), ('sub_approval_requested', 'Taşeron Hakedişi Onay Bekliyor'), ('sub_approved', 'Taşeron Hakedişi Onaylandı'), ('sub_rejected', 'Taşeron Hakedişi Reddedildi'), ('plan_approval_requested', 'Departman Talebi Onay Bekliyor'), ('plan_approved', 'Departman Talebi Onaylandı'), ('plan_rejected', 'Departman Talebi Reddedildi'), ('plan_dr_approved', 'Departman Talebi Planlama Onayladı'), ('drawing_released', 'Çizim Yayınlandı'), ('revision_requested', 'Revizyon Talep Edildi'), ('revision_approved', 'Revizyon Onaylandı'), ('revision_completed', 'Revizyon Tamamlandı'), ('revision_rejected', 'Revizyon Reddedildi'), ('job_on_hold', 'İş Beklemede'), ('job_resumed', 'İş Devam Ediyor'), ('topic_mention', 'Konuda Etiketlendiniz'), ('comment_mention', 'Yorumda Etiketlendiniz'), ('new_comment', 'Yeni Yorum'), ('password_reset', 'Parola Sıfırlama Talebi')], db_index=True, max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_emailed', models.BooleanField(default=False)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'notification_type', 'created_at'], name='notificatio_user_id_ef3643_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(db_index=True, max_length=60)),
                ('send_email', models.BooleanField(default=True)),
                ('send_in_app', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
