# Generated by Django 5.2.3 on 2026-03-11 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('pr_approval_requested', 'Satınalma Onayı Bekleniyor'), ('pr_approved', 'Satınalma Talebi Onaylandı'), ('pr_rejected', 'Satınalma Talebi Reddedildi'), ('pr_po_created', 'Satınalma Siparişi Oluşturuldu'), ('ot_approval_requested', 'Mesai Onayı Bekleniyor'), ('ot_approved', 'Mesai Talebi Onaylandı'), ('ot_rejected', 'Mesai Talebi Reddedildi'), ('qc_review_submitted', 'KK İncelemesi Gönderildi'), ('qc_review_approved', 'KK İncelemesi Onaylandı'), ('qc_review_rejected', 'KK İncelemesi Reddedildi'), ('ncr_created', 'NCR Oluşturuldu'), ('ncr_submitted', 'NCR Onaya Gönderildi'), ('ncr_approved', 'NCR Onaylandı'), ('ncr_rejected', 'NCR Reddedildi'), ('ncr_assigned', 'NCR Atandı'), ('sales_approval_requested', 'Satış Teklifi Onay Bekliyor'), ('sales_approved', 'Satış Teklifi Onaylandı'), ('sales_rejected', 'Satış Teklifi Reddedildi'), ('sales_consultation', 'Satış Danışma Talebi'), ('sales_converted', 'Teklif İş Emrine Dönüştürüldü'), ('sub_approval_requested', 'Taşeron Hakedişi Onay Bekliyor'), ('sub_approved', 'Taşeron Hakedişi Onaylandı'), ('sub_rejected', 'Taşeron Hakedişi Reddedildi'), ('plan_approval_requested', 'Departman Talebi Onay Bekliyor'), ('plan_approved', 'Departman Talebi Onaylandı'), ('plan_rejected', 'Departman Talebi Reddedildi'), ('plan_dr_approved', 'Departman Talebi Planlama Onayladı'), ('drawing_released', 'Çizim Yayınlandı'), ('revision_requested', 'Revizyon Talep Edildi'), ('revision_approved', 'Revizyon Onaylandı'), ('revision_completed', 'Revizyon Tamamlandı'), ('revision_rejected', 'Revizyon Reddedildi'), ('job_on_hold', 'İş Beklemede'), ('job_resumed', 'İş Devam Ediyor'), ('topic_mention', 'Konuda Etiketlendiniz'), ('comment_mention', 'Yorumda Etiketlendiniz'), ('new_comment', 'Yeni Yorum'), ('password_reset', 'Parola Sıfırlama Talebi')], max_length=60, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(blank=True, related_name='notification_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['notification_type'],
            },
        ),
    ]
