# Generated by Django 5.2.3 on 2026-03-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_notification_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationroute',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
