# Generated by Django 5.2.3 on 2026-03-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_route_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationroute',
            name='teams',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
