# Generated by Django 5.2.3 on 2026-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_update_sales_consultation_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('design', 'Tasarım'), ('procurement', 'Satınalma'), ('quality_control', 'Kalite Kontrol'), ('sales', 'Satış'), ('planning', 'Planlama'), ('topics', 'Konular'), ('general', 'Genel')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
