# Generated by Django 5.2.3 on 2026-05-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0023_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='user_groups',
            field=models.JSONField(blank=True, default=list, help_text='UserGroup names whose members receive this notification.'),
        ),
    ]
