# Generated by Django 5.2.3 on 2026-05-13 12:01

from django.db import migrations


def fix_group_dept_codes(apps, schema_editor):
    NotificationConfig = apps.get_model('notifications', 'NotificationConfig')
    for cfg in NotificationConfig.objects.exclude(groups=[]):
        updated = [g.removesuffix('_team') for g in cfg.groups]
        if updated != cfg.groups:
            cfg.groups = updated
            cfg.save(update_fields=['groups'])


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0024_notificationconfig_user_groups'),
    ]

    operations = [
        migrations.RunPython(fix_group_dept_codes, migrations.RunPython.noop),
    ]
