# Generated by Django 5.2.3 on 2026-06-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0026_add_job_cancelled_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconfig',
            name='user_groups',
            field=models.JSONField(blank=True, default=list, help_text='UserGroup IDs whose members receive this notification.'),
        ),
    ]
