# Generated by Django 5.2.3 on 2026-04-10 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.PositiveIntegerField(default=150, help_text='GPS geofence radius in metres (for future blue-collar use).')),
                ('allowed_ip_ranges', models.JSONField(default=list, help_text='List of CIDR strings for office IP ranges, e.g. ["192.168.1.0/24", "10.0.0.5/32"].')),
            ],
            options={
                'verbose_name': 'Attendance Site',
                'verbose_name_plural': 'Attendance Sites',
            },
        ),
        migrations.CreateModel(
            name='ShiftRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_location', models.CharField(choices=[('workshop', 'Atölye'), ('office', 'Ofis'), ('all', 'Tümü')], default='all', max_length=10)),
                ('expected_start', models.TimeField(help_text='Shift start time (e.g. 08:00).')),
                ('expected_end', models.TimeField(help_text='Shift end time (e.g. 17:00).')),
                ('overtime_threshold_minutes', models.PositiveIntegerField(default=15, help_text='How many minutes past expected_end before overtime is flagged.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shift Rule',
                'verbose_name_plural': 'Shift Rules',
                'ordering': ['work_location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('ip', 'IP (Office Network)'), ('gps', 'GPS Geofence'), ('manual_override', 'Manual Override Request'), ('hr_manual', 'HR Manual Entry')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active (Checked In)'), ('complete', 'Complete (Checked Out)'), ('pending_override', 'Pending HR Override Approval'), ('override_rejected', 'Override Rejected')], default='active', max_length=20)),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-check_in_time'],
                'indexes': [models.Index(fields=['user', 'date'], name='attendance__user_id_f0d554_idx'), models.Index(fields=['date'], name='attendance__date_337b1d_idx'), models.Index(fields=['status'], name='attendance__status_741eb8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_attendance_user_date')],
            },
        ),
    ]
