# Generated by Django 5.2.3 on 2026-04-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_check_in_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='checkout_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('active', 'Active (Checked In)'), ('complete', 'Complete (Checked Out)'), ('pending_override', 'Pending HR Check-in Override Approval'), ('pending_checkout_override', 'Pending HR Check-out Override Approval'), ('override_rejected', 'Override Rejected')], default='active', max_length=30),
        ),
    ]
