# Generated by Django 5.2.3 on 2026-04-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_checkout_override_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='checkout_override_reason',
        ),
    ]
