# Generated by Django 5.2.3 on 2026-04-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendancerecord_checkout_override_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='method',
            field=models.CharField(choices=[('ip', 'IP (Ofis Ağı)'), ('gps', 'GPS'), ('manual_override', 'Manuel Değişim Talebi'), ('hr_manual', 'Manuel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif (Giriş Yapıldı)'), ('complete', 'Tamamlandı (Çıkış Yapıldı)'), ('pending_override', 'İnsan Kaynakları Onayı Bekliyor (GİRİŞ)'), ('pending_checkout_override', 'İnsan Kaynakları Onayı Bekliyor (ÇIKIŞ)'), ('override_rejected', 'Reddedildi')], default='active', max_length=30),
        ),
    ]
