# Generated by Django 5.2.3 on 2026-04-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancerecord_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftrule',
            options={'ordering': ['name'], 'verbose_name': 'Shift Rule', 'verbose_name_plural': 'Shift Rules'},
        ),
        migrations.RemoveField(
            model_name='shiftrule',
            name='work_location',
        ),
        migrations.AddField(
            model_name='shiftrule',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Used for users with no explicit shift rule assigned. Only one rule should be default.'),
        ),
    ]
