# Generated by Django 5.2.3 on 2026-04-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_publicholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='early_leave_minutes',
            field=models.IntegerField(default=0, help_text='Minutes before expected_end the user checked out. 0 = stayed full shift or later.'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='late_minutes',
            field=models.IntegerField(default=0, help_text='Minutes after expected_start the user checked in. 0 = on time or early.'),
        ),
    ]
