# Generated by Django 5.2.3 on 2026-04-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendancerecord_early_leave_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('annual_leave', 'Yıllık İzin'), ('sick_leave', 'Hastalık İzni'), ('maternity_leave', 'Doğum İzni'), ('paternity_leave', 'Babalık İzni'), ('bereavement_leave', 'Ölüm İzni'), ('marriage_leave', 'Evlilik İzni'), ('public_duty', 'Resmi Görev'), ('compensatory_leave', 'Mazeret İzni'), ('business_trip', 'Görev Seyahati'), ('half_day', 'Yarım Gün'), ('unpaid_leave', 'Ücretsiz İzin'), ('unauthorized_absence', 'İzinsiz Devamsızlık')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif (Giriş Yapıldı)'), ('complete', 'Tamamlandı (Çıkış Yapıldı)'), ('pending_override', 'İnsan Kaynakları Onayı Bekliyor (GİRİŞ)'), ('pending_checkout_override', 'İnsan Kaynakları Onayı Bekliyor (ÇIKIŞ)'), ('override_rejected', 'Reddedildi'), ('leave', 'İzinli')], default='active', max_length=30),
        ),
    ]
