# Generated by Django 5.2.3 on 2026-04-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendancerecord_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
