# Generated by Django 5.2.3 on 2026-04-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendancerecord_check_in_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='overtime_hours',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='overtime_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
