# Generated by Django 5.2.3 on 2026-04-14 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_rename_overtime_hours_to_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('annual_leave', 'Yıllık İzin'), ('sick_leave', 'Hastalık İzni'), ('maternity_leave', 'Doğum İzni'), ('paternity_leave', 'Babalık İzni'), ('bereavement_leave', 'Ölüm İzni'), ('marriage_leave', 'Evlilik İzni'), ('public_duty', 'Resmi Görev'), ('compensatory_leave', 'Mazeret İzni'), ('business_trip', 'Görev Seyahati'), ('half_day', 'Yarım Gün'), ('paid_leave', 'Ücretli İzin'), ('unpaid_leave', 'Ücretsiz İzin'), ('unauthorized_absence', 'İzinsiz Devamsızlık')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='method',
            field=models.CharField(choices=[('ip', 'IP (Ofis Ağı)'), ('gps', 'GPS'), ('manual_override', 'Manuel Değişim Talebi'), ('hr_manual', 'HR Değişikliği')], max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='notes',
            field=models.TextField(blank=True, help_text='HR notes. For leave records, use this to record leave context (e.g. approval info, compensatory details).'),
        ),
        migrations.CreateModel(
            name='AttendanceLeaveInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('leave_type', models.CharField(choices=[('annual_leave', 'Yıllık İzin'), ('sick_leave', 'Hastalık İzni'), ('maternity_leave', 'Doğum İzni'), ('paternity_leave', 'Babalık İzni'), ('bereavement_leave', 'Ölüm İzni'), ('marriage_leave', 'Evlilik İzni'), ('public_duty', 'Resmi Görev'), ('compensatory_leave', 'Mazeret İzni'), ('business_trip', 'Görev Seyahati'), ('half_day', 'Yarım Gün'), ('paid_leave', 'Ücretli İzin'), ('unpaid_leave', 'Ücretsiz İzin'), ('unauthorized_absence', 'İzinsiz Devamsızlık')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_intervals', to='attendance.attendancerecord')),
            ],
            options={
                'verbose_name': 'Leave Interval',
                'verbose_name_plural': 'Leave Intervals',
                'ordering': ['start_time'],
            },
        ),
    ]
