# Generated by Django 5.2.3 on 2026-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_add_leave_interval_and_paid_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholiday',
            name='is_half_day',
            field=models.BooleanField(default=False, help_text='True for Arife (bayram eve) — work ends at noon.'),
        ),
    ]
