# Generated by Django 5.2.3 on 2026-06-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_attendancesession_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='early_leave_minutes',
            field=models.IntegerField(default=0, help_text='Minutes before expected_end the last session ended. 0 = stayed full shift or later.'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='late_minutes',
            field=models.IntegerField(default=0, help_text='Minutes after expected_start the first session started. 0 = on time or early.'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='notes',
            field=models.TextField(blank=True, help_text='HR notes. For leave records, use this to record leave context.'),
        ),
    ]
