# Generated by Django 5.2.3 on 2026-02-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salesoffer',
            new_name='sales_sales_status_3175ad_idx',
            old_name='sales_salesoffer_status_customer_idx',
        ),
        migrations.RenameIndex(
            model_name='salesofferpricerevision',
            new_name='sales_sales_offer_i_cab761_idx',
            old_name='sales_pricerev_offer_current_idx',
        ),
        migrations.RenameIndex(
            model_name='salesofferpricerevision',
            new_name='sales_sales_offer_i_e2d931_idx',
            old_name='sales_pricerev_offer_round_idx',
        ),
        migrations.AlterField(
            model_name='salesoffer',
            name='customer_inquiry_ref',
            field=models.CharField(blank=True, help_text="Customer's own PO or reference number", max_length=100),
        ),
        migrations.AlterField(
            model_name='salesofferitem',
            name='title_override',
            field=models.CharField(blank=True, help_text='Overrides template_node.title for the created job order title', max_length=255),
        ),
    ]
