# Generated by Django 5.2.3 on 2026-02-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_sales_salesoffer_status_customer_idx_sales_sales_status_3175ad_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffer',
            name='offer_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
