# Generated by Django 5.2.3 on 2026-03-05 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_joborder_source_offer'),
        ('sales', '0003_offer_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoffer',
            name='converted_job_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_offer', to='projects.joborder'),
        ),
    ]
