# Generated by Django 5.2.3 on 2026-03-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salesoffer_converted_job_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesofferitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='salesofferitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
