# Generated by Django 5.2.3 on 2026-03-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesoffer_incoterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='offertemplatenode',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
