# Generated by Django 5.2.3 on 2026-03-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_offertemplatenode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertemplatenode',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
