# Generated by Django 5.2.3 on 2026-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_offertemplatenode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoffer',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('consultation', 'Danışma'), ('pricing', 'Fiyatlandırma'), ('pending_approval', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('submitted_customer', 'Müşteriye Sunuldu'), ('won', 'Kazanıldı'), ('converted', 'İş Emrine Dönüştürüldü'), ('lost', 'Kaybedildi'), ('cancelled', 'İptal Edildi')], db_index=True, default='draft', max_length=30),
        ),
    ]
