# Generated by Django 5.2.3 on 2026-03-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0035_purchaseorderline_delivered_at_and_more'),
        ('sales', '0009_add_converted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffer',
            name='delivery_place',
            field=models.CharField(blank=True, help_text='Teslim yeri', max_length=255),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='order_no',
            field=models.CharField(blank=True, help_text='Sipariş no', max_length=100),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='payment_terms',
            field=models.ForeignKey(blank=True, help_text='Ödeme şekli', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_offers', to='procurement.paymentterms'),
        ),
        migrations.AddField(
            model_name='salesofferitem',
            name='delivery_period',
            field=models.CharField(blank=True, help_text="Termin süresi (örn. '4 ay', '6 hafta')", max_length=100),
        ),
    ]
