# Generated by Django 5.2.3 on 2026-03-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_add_delivery_place_payment_terms_order_no_delivery_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffer',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nakliye bedeli (tarafımızca üstlenilirse toplam fiyata eklenir)', max_digits=16),
        ),
        migrations.AlterField(
            model_name='salesofferfile',
            name='file_type',
            field=models.CharField(choices=[('drawing', 'Çizim'), ('specification', 'Şartname'), ('quotation', 'Fiyat Teklifi'), ('correspondence', 'Yazışma'), ('photo', 'Fotoğraf'), ('receipt', 'Proforma'), ('other', 'Diğer')], default='other', max_length=20),
        ),
    ]
