# Generated by Django 5.2.3 on 2026-04-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_add_shipping_price_to_salesoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesofferitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Explicit parent item — makes this a custom sub-item of the parent on conversion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sales.salesofferitem'),
        ),
    ]
