# Generated by Django 5.2.3 on 2026-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesofferitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffer',
            name='pricing_mode',
            field=models.CharField(choices=[('flat', 'Düz — fiyat kök kalemlere girilir'), ('leaf', 'Yaprak — fiyat yaprak kalemlere girilir, ebeveynler toplanır')], default='flat', help_text='flat: price on root items; leaf: price on leaf items, parents roll up', max_length=10),
        ),
    ]
