# Generated by Django 5.2.3 on 2026-06-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_add_pricing_mode_to_salesoffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesofferitem',
            options={'ordering': ['offer', 'sequence', 'id'], 'verbose_name': 'Teklif Kalemi', 'verbose_name_plural': 'Teklif Kalemleri'},
        ),
    ]
